### ISSUE TITLE
Content Security Policy is not sufficiently implemented

### ISSUE THREAD

**Issue by jclemens** [tprouvot/Salesforce-Inspector-reloaded#100]
The Content Security Policy (CSP) is not sufficiently implemented to protect against various attacks. A missing or non-restrictive Content Security Policy can significantly increase the risk and impact of cross-site scripting attacks in modern browsers. Due to this our company policy prevents us from using this very good addon. 

Please properly implement Content Security Policy according to following documentation for Firefox and Chrome:
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_Security_Policy
- https://developer.chrome.com/docs/extensions/mv3/manifest/content_security_policy/

Additional Information:
- https://en.wikipedia.org/wiki/Content_Security_Policy
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
- https://www.w3.org/TR/CSP3/

**Comment by tprouvot** [comment]
Hi @jclemens ! 
Thanks for this suggestion, how about creating a PR with the Content Security Policy required by your company ? 😃
