### ISSUE TITLE
[data-export] Buttons "create csv file" "create excel file"

### ISSUE THREAD

**Issue by mickaelgudin** [tprouvot/Salesforce-Inspector-reloaded#101]
@tprouvot often times I see people use the extension by copy pasting the content in excel. I believe this enhancement would allow people to avoid this copy pasting by providing a link to download the export file.

Copy buttons would still be useful.

**Comment by Astisme** [comment]
This would be very useful. Is anyone looking into it?

**Comment by tprouvot** [comment]
Hi @Astisme not at the moment

**Comment by tprouvot** [comment]
Hi @mickaelgudin,
This will be released in 1.24 !

**Comment by tprouvot** [comment]
<img width="640" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/ed9cc337-9a58-4344-a92d-39c74e855a0e">
