### ISSUE TITLE
Org Id List

### ISSUE THREAD

**Issue by sfscgjohnson** [tprouvot/Salesforce-Inspector-reloaded#113]
**Is your feature request related to a problem? Please describe.**
I frequently need to give Salesforce Support my org ids and there is no consolidated way to see them all.
For Prod or inside a specific Sandbox you have to go to Company Information.   For Any other sandbox besides the one you are on you have to go to Sandboxes.
In these cases, it sometimes only gives you the 15 char id instead of the 18.

**Describe the solution you'd like**
A new tab that lists all the Org Id's with 3 fields 
18 Char org id - easily copy able to the clipboard
Org Name
Org Instance Name
This would be a two/three click process.  Open Inspector, Click Org Ids, Click on Org Id you want to copy.

**Describe alternatives you've considered**
Spreadsheets,  Copy paste storage, Notepad, One Note

**Comment by tprouvot** [comment]
Hi @sfscgjohnson,
Thanks for submitting this feature request !

I can see two ways to address your need with current implementation and I was wondering if you have considered it ?

### Get production id :

1. From shortcut tab, search for company information en press enter

<img width="280" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/09a019d4-54be-4eb5-b54c-8cb396f335e9">

2. From Data export by running and saving the query
`SELECT Id, Name, InstanceName, DefaultLocaleSidKey, TimeZoneSidKey FROM Organization`

### Retrieve sandboxes id:
From data export, run a save as "Sandboxes" the following query (with tooling api enabled)
<img width="1089" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/727d669a-b64f-4a02-92bb-1e10f88b08cb">
`SELECT Id, SandboxName, Description, LicenseType, HistoryDays FROM SandboxInfo`
When clicking on the Id, you have the option "Copy Id"
<img width="164" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/67f2a1bb-c34b-4d4f-9fdc-fe7a2915dd96">


With those options you only have 18 char ids.
What do you think about it ?

**Comment by tprouvot** [comment]
Hi @sfscgjohnson did you had a chance to read my previous comment ?

**Comment by tprouvot** [comment]
Hi @sfscgjohnson, 
Since there's no answer from your part on the solutions I provided, I'll close this issue.

If you're not ok with this, feel free to re-open the issue and we will check what we can do.
