### ISSUE TITLE
[popup] Use custom shortcuts

### ISSUE THREAD

**Issue by tprouvot** [tprouvot/Salesforce-Inspector-reloaded#115]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to customize shortcuts by adding new ones.

ie. setup sections that are not in all orgs and specific to a particular cloud or link to specific records.

The addition / deletion of links is made by editing property "$orgDomain_orgLinks" in the web browser localStorage:
In order to know what is your domain you can check for another property "orgInstance"

![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/d1f37f99-3d47-41c3-a3cd-892502c4523d)

Here's an example of the content of the property :

``` json
[
  {
    "label": "Test myLink",
    "link": "/lightning/setup/SetupOneHome/home",
    "section": "Custom",
    "prod": false
  },
  {
    "label": "EnhancedProfiles",
    "section": "Setup",
    "link": "/lightning/setup/EnhancedProfiles/home",
    "prod": false
  }
]

```

![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/f5b9925e-ec1a-411f-82bf-fe0bc7ba2846)

**Comment by saicharanreddyk** [comment]
@tprouvot  Can we make this to work "$orgDomain_orgLinks" with all the domains??  Currently we need to have custom links for every org. Any thoughts?

**Comment by tprouvot** [comment]
@saicharanreddyk I think I can remove the org domain from the property name and handle it in the json.
It would look like this

``` json 
[
  {
    "label": "Test myLink",
    "link": "/lightning/setup/SetupOneHome/home",
    "domain": ""
    "section": "Custom",
    "prod": false
  },
  {
    "label": "EnhancedProfiles",
    "section": "Setup",
    "link": "/lightning/setup/EnhancedProfiles/home",
    "domain": "myDomain.salesforce.com"
    "prod": false
  }
]
```
I have to think about it because it will affect users who actually use it today.

@saicharanreddyk  Could you create a new enhancement with this requirement a a link to this discussion ?
