### ISSUE TITLE
Profile Shortcut returns 'Page not found' if Enhanced Profiles UI is turned on

### ISSUE THREAD

**Issue by chelseastrong** [tprouvot/Salesforce-Inspector-reloaded#120]
**Describe the bug**
If Enhanced Profiles is turned on in User Management Settings, and you click on the Profiles shortcut, it takes you to a page that says "Page not found".

**To Reproduce**
1. In User Management Settings in Salesforce, turn on Enhanced Profile List Views and Enhanced Profile User Interface.
2. In the extension, click on Shortcuts.
3. Search for "profiles" and click on the result.
4. See page not found error.

**Expected behavior**
If Enhanced Profiles is turned on, the page should direct you to https://orgname.lightning.force.com/lightning/setup/EnhancedProfiles/home

**Desktop (please complete the following information):**
 - OS: macOS Ventura
 - Browser: Chrome 114.0.5735.198
 - Version 1.18

**Comment by tprouvot** [comment]
Hi @chelseastrong,
You're completely right ! 
I found out this issue one or two weeks ago and added a new shortcut for Enhanced Profile.

This issue will be fixed in the next version which should be released in one or two weeks! 🚀

**Comment by tprouvot** [comment]
<img width="418" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/150579a4-bd61-4813-a461-3532e3714f61">

**Comment by tprouvot** [comment]
If you want to try it, you can install locally the releaseCandidate branch which is the future version 1.19 containing this fix

**Comment by tprouvot** [comment]
@chelseastrong If you were searching for a particular profile, this new feature (also delivered in 1.19) should help you:
You'll be able to search for profiles (by name) in the shortcut tab

![2023-07-10_11-50-41 (1)](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/e1f53840-d290-4b39-86fd-fc8df409cd5d)
