### ISSUE TITLE
[data-export] Export Query Link is not Embeddable in HTML or clickable in Messaging Platform Slack.  

### ISSUE THREAD

**Issue by rpsherry-starburst** [tprouvot/Salesforce-Inspector-reloaded#123]
**Describe the bug**
In release 1.19 the ability to export a query was added from the data export page.
This does allow you to export a link. Unfortunately this link cannot be embedded in html or linked in a chat like slack. 
The only way the link works is if someone copies the link into a browser directly. So not exactly a bug, but this limits usablility.

Based on my research it seems that this is expected behavior from anything linking to a chrome extensions resources.
Might need a new method to make this work. 

**To Reproduce**
1. Open salesforce
2. Open inspector
3. Dataexport
4. write a query ex: `SELECT ID FROM ACCOUNT`
5. click Export query
6. post in slack or add to a html page via <a href="[chrome-extension://](chrome-extension://hpijlohoihegkfehhibggnkbjhoemldh/data-export.html......">link to query</a>
7. nothing happens link unclickable

**Expected behavior**
Link is embeddable and clickable

**Comment by rpsherry-starburst** [comment]
Rough idea, since linking to a chrome extensions resources like "data-export.html" is impossible. Maybe a redirect would work?

example: 

1. User clicks "export query" a url to a webserver is generated say `"https://inspector-reloaded.com?q=SELECT+ID+FROM+ACCOUNT`
2. When that url is accessed it automatically re-directs locally to `chrome-extension://data-dexport?q=SELECT+ID+FROM+ACCOUNT`

**Comment by tprouvot** [comment]
I'm afraid this is really overkill to set up a website just to redirect to the extension (and not sure it would work also 😬).
I'm sorry Ryan but I don't have any suggestion for this issue, please let me know if you have other ideas, I'll re-open the issue.

Have a great day !
