### ISSUE TITLE
[data-export] Assist users on autocompleting there SOQL 

### ISSUE THREAD

**Issue by ehsky** [tprouvot/Salesforce-Inspector-reloaded#130]
Thank you for taking continuing the development of salesforce inspector! Awesome feature updates ☺️ 

**Is your feature request related to a problem? Please describe.**
It would be great to give end users assistance on finding the correct fields and functions when writing a SOQL in "Export Data"

**Describe the solution you'd like**
When a user starts typing in the "Export Query" input window a drop down menu under there line cursers is shown after they start typing. The text that is typed is the search tearm on fields for the querying object or SQL functions. 

**Describe alternatives you've considered**
- Include SOQL functions in the suggested section. 
- Include a view all button for all suggested fields section. 
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/26760784/3f8f599e-01a6-4823-b224-6eceea793ee4)

**Additional context**

Example implementation of a drop down assistive autocomplete menu.
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/26760784/e4bc8f81-2f57-4bbd-b847-b63fc14f35e6)

Next wish would be to extend with functions
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/26760784/b8d9a46f-7195-462a-a5aa-0f758ba143ae)

The examples can be tested and are implemented in this repo https://lwc-soql-builder.github.io/lwc-soql-builder/

**Comment by tprouvot** [comment]
Hi @ehsky, 
Thanks for this feature request ! 
I don't know if you already checked this but there's already a button to display all suggested fields and functions:

<img width="1416" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/30b817d3-2cc4-4961-9f3a-0be58d40ff2f">

For the dropdown assistive menu, you can already use the tab key to navigate among suggestions and enter to select one

![2023-07-24_16-36-17 (1)](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/47e8f8b7-378c-45d0-a68f-b3f87b7ec0f8)

**Comment by ehsky** [comment]
Thanks @tprouvot i was not aware the tab functionality and the show all. 
I assume this as closed then
