### ISSUE TITLE
[data-export] Include a SOSL editor

### ISSUE THREAD

**Issue by ehsky** [tprouvot/Salesforce-Inspector-reloaded#131]
**Is your feature request related to a problem? Please describe.**

I still use https://workbench.developerforce.com/ to create SOSL query's as i have not found a better alternative out there. Would be great to have this in the same plugin as Salesforce Inspector. 

**Describe the solution you'd like**
In the "Data-export" window i would like a button/switch/tab to go to a SOSL editor. 
In the SOSL editor i would like to be able to create SOSL queries as text input. 

**Describe alternatives you've considered**
- Extended SOSL version would be to give end users a UI to create the SOSL req similar to https://workbench.developerforce.com/. 

![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/26760784/93e326c7-8807-460d-841c-3c2fd3df0b3e)

**Comment by dufoli** [comment]
@tprouvot can you assign to me. I have well advanced (autocomplete 50%, execute 100%)

**Comment by dufoli** [comment]
@ehsky done in my fork : https://github.com/dufoli/Salesforce-Inspector-Advanced
https://chromewebstore.google.com/detail/salesforce-inspector-adva/dbfimaflmomgldabcphgolbeoamjogji

**Comment by tprouvot** [comment]
Hi @ehsky
This should be available soon in the beta version, would you like to do some tests ?

**Comment by tprouvot** [comment]
Thank you very much for testing @ehsky 🙏 👏 
Yes I'm thinking about adding the suggestions also, just wanted to provide a quick way to support SOSL and GraphQL requests first.
