### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by 8bit-cutie** [tprouvot/Salesforce-Inspector-reloaded#133]
**Is your feature request related to a problem? Please describe.**
Adding the option to enable keyboard shortcuts to easily and quickly access tool. Currently users have to click on SF Inspector for it to open up, then click on either Show all, Data Export, etc. 

**Describe the solution you'd like**
Adding a keyboard shortcut to open SF Inspector menu. 

**Describe alternatives you've considered**

**Additional context**

**Comment by tprouvot** [comment]
Hi @8bit-cutie ,

The shortcut already exists and the keys to press are displayed on the bottom of the pop-up. 
Have you already tried it ?

**Comment by tprouvot** [comment]
@8bit-cutie d
Warning : the shortcut is different from mac and windows, you can find it here:

<img width="278" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/5d37103e-ffee-4f39-b3c8-524a38aa5d35">
