### ISSUE TITLE
[data-import]Ability to define csv-file separator

### ISSUE THREAD

**Issue by foxysolutions** [tprouvot/Salesforce-Inspector-reloaded#144]
**Challenge/request/solution**
I'm receiving a csv file from another system, having commas in text (without surrounding-quotes) and with ;-separators. While I can prepare this easily in the file, I think it might be a nice addition for the csv-import to be able to indicate what separator to use

**Describe alternatives you've considered**
Regular expression, as value with , is at the end of the file so I can surround the text with commas as part of the text, but this is time consuming and less nice

**Additional context**
Awesome work with this plugin, keep it going!!

**Comment by tprouvot** [comment]
Hi @foxysolutions,

Would you mind test the feature by checking out the branch [feature/defineCsvSeparator](https://github.com/tprouvot/Salesforce-Inspector-reloaded/tree/feature/defineCsvSeparator) and install this version [locally](https://github.com/tprouvot/Salesforce-Inspector-reloaded#chrome) ?

Then you should be able to update the separator by setting the local property value

![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/0f4bf47c-a216-4f85-96b6-6f8e35efccbb)
