### ISSUE TITLE
[popup] Ability to move popup icon

### ISSUE THREAD

**Issue by Tratius** [tprouvot/Salesforce-Inspector-reloaded#145]
**Is your feature request related to a problem? With the new Winter'24 release, Flows open the config window of an element to the right. The x to close the window is very close or right under the SF inspector widget Access triangle. 

**Describe the solution you'd like**
I would like to ask to move the triangle Widget or allow an option to choose the location of the widget within the website window.

**Describe alternatives you've considered**
No Alternatives so far. I will be thinking about any from this moment forward. 

**Additional context**
Add any other context or screenshots about the feature request 
![SF inspector clip](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/143458002/885501ff-970e-4607-a558-e3b3d24dedb2)
here.

**Comment by tprouvot** [comment]
Hi @Tratius,
Thanks for this feature request !

I think you won't be the only one to enjoy this feature, I've already notice similar problem on Firefox.
Waiting for the dev of this feature, you still have the ability to open it with the shortcut:

<img width="274" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/7e438e84-2e29-41d6-815c-c029e68360e4">

**Comment by baobao917** [comment]
Not sure how to upvote this request, but I wholeheartedly agree.  The new Winter 24 change has the "x" icon right under where the SF Inspector tab is.  Would love the ability to move the tab up/down or or the right side/left side of the screen.

![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/104730171/60dc9a9a-1661-424d-9b05-c54791e7b0d9)

**Comment by tprouvot** [comment]
Hi @baobao917,

You did it the right way! 👍
I should be able to do something for the next extension's release. 
I'll post updates on this issue to keep you informed!

**Comment by tprouvot** [comment]
Hi @baobao917 @Tratius ,
I can tell you that thanks to @pietromartino something great is coming ...
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/ef560066-b98d-4423-b18c-8748442d5dbd)

**Comment by baobao917** [comment]
Looking fwd to it!

**Comment by Tratius** [comment]
Thanks so much! I am also looking forward to it!

**Comment by tprouvot** [comment]
Available in the next version and soon on the beta version ! 🚀
