### ISSUE TITLE
Org instance info does not update

### ISSUE THREAD

**Issue by hvilminko** [tprouvot/Salesforce-Inspector-reloaded#167]
Our customer's Salesforce org recently moved to a new instance. After the migration I noticed that the instance information shown by Inspector was still pointing to the old one. I deleted the "orgInstance" key-value pair in local storage and a new value got created after next login. But should the instance be updated automatically without need for manual tweaking?

**Comment by tprouvot** [comment]
Hi @hvilminko,
You're right the value is stored in localStorage to avoid multiples callout for something is not supposed to change really often .
Was this change occurred after a support case to switch org instance to a preview / non preview ?
I can consider to perform the query each time but I though it would be overkill.

We have a feature in development to add a new tab "Org Info" which will display org instance, current version / patch and coming releases dates. When it will be release, I'll remove the org instance info from the pop up to relocate it in the new tab

**Comment by hvilminko** [comment]
In this case the customer's orgs were migrated to Hyperforce which seems to be a growing trend, but org migrations sometimes happen for other reasons as well. They are indeed quite rare but would it be reasonable to query `SELECT InstanceName FROM Organization` once per session? Otherwise the instance name will stay the same forever?

**Comment by tprouvot** [comment]
Hi @hvilminko 
This will be fixed in 1.21 version

**Comment by hvilminko** [comment]
For now I have manually deleted the values for a couple of orgs that have been migrated to Hyperforce. But it's good to know that this will not be needed in the future!
