### ISSUE TITLE
Case and Lead Owner gets updated to Default Owner when any field value is updated thru Show All Data

### ISSUE THREAD

**Issue by dthurupu** [tprouvot/Salesforce-Inspector-reloaded#168]
**Describe the bug**
Case Record: If you try to update any field value from Show All Data. then after save, Case owner will automatically updated to the default owner set under Support Settings (Salesforce Setup => Support Settings => Default Case Owner)

Lead Record: If you try to update any field value from Show All Data. then after save, Lead owner will automatically updated to the default owner set under Lead Settings (Salesforce Setup => Lead Settings => Default Lead Owner)

**To Reproduce**
For Case Record: 
1. Open any Salesforce case record (where case owner is not the Default Case Owner)
2. Open Salesforce Inspector Extension from record and click on Show all data
3. Edit any field value
4. Click Save
5. Go back to the case record and now you will see the Case owner updated to Default Case Owner. 

For lead Record: 
Follow same steps as case but for Lead record.

**Expected behavior**
After updating any field value using Inspector, Case/Lead owner should remain same.

**Screenshots**

**Desktop:**
 - OS: Windows 11
 - Browser - Chrome
 - Version - 117.0.5938.92

**Comment by tprouvot** [comment]
Hi @dthurupu, 
This is normal behaviour and should be the same when you update the record from Salesforce UI right ?

I do not consider it as a bug from Salesforce Inspector but something linked to your implementation.
I'll close the issue since this is not related to the extension, you can re-open it if you do not agree and we will discuss about it

**Comment by tprouvot** [comment]
Hi @dthurupu,
It seems that my initial answer was wrong, someone create a feature request that may address your need.
I'll probably implement something to address this need, I'll post updates on the following feature request : #198
