### ISSUE TITLE
Insert Suggestions for Picklist Values with Ctrl+Space

### ISSUE THREAD

**Issue by ogomezba** [tprouvot/Salesforce-Inspector-reloaded#170]
Hi everyone! I've always missed the functionality in the Inspector to autocomplete picklist values with Ctrl+Space. It always felt strange to me that such useful functionality didn't work in the same way as the Ctrl+Space does for fields.

However, by recently looking in the repo and the code, I understood what the Ctrl+Space functionality was about for field values (and found it really cool!). However, now that I've seen that, I still feel it would be more useful for the concrete case of picklist fields to insert the autocomplete suggestions instead of performing the query that is being done right now. I can see a few usages for that (like quickly checking which values are really being used before filtering when trying to find some test data) but those look quite niche to me if compared with the normal insertion of the suggestions.

So, I decided to open this issue to check other's opinions on this as I would gladly implement this if there is any agreement.

The solution that I would prefer (but I'm obviously biased to my own usage) would be to keep everything as it is but change the behaviour for Ctrl+Space for picklist values to insert the suggestions instead of performing the query.

Another option would be to include it as an opt-in option for the user.

Finally, a different shortcut could be used for it even though it would feel strange to have the "same functionality" in different shortcuts depending on if you are completing a field.

What are your feelings about this?

**Comment by tprouvot** [comment]
Hi @ogomezba,

Ctrl + space triggers the autocomplete fields functionality (adds all the fields for the sobject).
Ctrl + enter runs the query

The extension detects when you are performing a filter on a picklist field to propose you the different values availables
<img width="998" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/78831fa4-e9eb-4806-980c-97d773a4167c">

You can already navigate to those suggestions with tab key and then run the query with ctrl + enter.

I'm not sure to understand your need? Is it to add all the picklist values in a where clause such as 

`SELECT Id, Status FROM Case where Status =`
 Ctrl + space 
 `SELECT Id, Status FROM Case where Status ='Cancelled' or Status ='Closed' ....`

**Comment by ogomezba** [comment]
Hi @tprouvot,

Yes, I was thinking about the example that you mentioned but specifically the scenario where you have already typed part of the picklist value so only one option is still offered (the one that I want) and I just want to insert that option. Something like:

`SELECT Id, Status FROM Case WHERE Status = clo`
Ctrl + Space
`SELECT Id, Status FROM Case WHERE Status = 'Closed'`

But, as you pointed out, I did not consider the option of just pressing Tab and Enter to insert the option (silly me). I was previously clicking on the suggested option.

Considering that, it is already good enough!

Thank you for your answer.

**Comment by Eric-2369** [comment]
Hi @tprouvot 
Thank you very much for adding this feature. However, I've encountered a problem where, in macOS, control+space is the default shortcut for switching input methods, which conflicts with this function. Is it possible to change this shortcut for the plugin in the macOS environment?

**Comment by tprouvot** [comment]
Hi @Eric-2369,

As discussed with Oscar, the "Ctrl+Space" shortcut is used to add all fields from an sobject to the query.

I'm using Mac and have no issue with the shortcut. Maybe it's a configuration / other plugin on your computer?

I won't change the shortcut since this would be a breaking change for all the Mac users who are used to it.

**Comment by Eric-2369** [comment]
Hi @tprouvot 
I checked Apple's documentation (https://support.apple.com/guide/mac-help/write-in-another-language-on-mac-mchlp1406/mac), and indeed, Control+Space is one way to switch input methods. The original text states: 'You can also press Control-Space bar to select the last input source you used. I also tested my colleague's MacBook and confirmed that this shortcut is used to switch input methods.

**Comment by tprouvot** [comment]
@Eric-2369 
https://apple.stackexchange.com/questions/423971/disable-controlspace-keyboard-shortcut
