### ISSUE TITLE
Add Hotkeys/Shortcuts

### ISSUE THREAD

**Issue by asanaEAzimzhanov** [tprouvot/Salesforce-Inspector-reloaded#171]
The one missing part of both - original and reloaded extensions are hotkeys. I'd like to have an ability to configure hotkeys using "Keyboard Shortcuts" menu in "chrome://extensions/" path.

For start, that would be ideal to navigate to "Data Export", "Data Import" using hotkeys.

Thank you!

**Comment by Damecek** [comment]
This is partially possible, the shortcut for opening the side window is `[ctrl + option + i]` on OSX
<img width="278" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/46635736/714615e9-4233-451a-8d4f-fabe49c4575f">

And then `A` key will open _Show all data_ and `E` key will open _Data Export_.

What is missing is surfacing this to the `chrome://extensions/` path, so we could remap the `[ctrl + option + i]`. And also navigation between the _Objects, User, Shortcuts_ tabs. Ultimately to have another 3 configurable shortcuts which would automatically open the side panel already in one of the 3 tabs. 

Like:

- `[ctrl + option + i]`: opens _Objects_
- `[ctrl + option + u]`: opens _Users_
- `[ctrl + option + x]`: opens _Shortcuts_

**Comment by Damecek** [comment]
It could work similarly to Lightning [Navigator](https://chrome.google.com/webstore/detail/salesforce-navigator-for/pbjjdhghffpemcglcadejmkcpnpmlklh?utm_source=ext_sidebar&hl=en-GB), one shortcut to open the search bar, type the page and on enter redirect there.

**Comment by tprouvot** [comment]
Guys it's coming ...

<img width="660" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/382aea2d-5278-4dfe-89e6-6dcec4c724c9">

@Damecek I'll explore the options we have to leverage this for popup tabs also 👍

**Comment by Damecek** [comment]
Hi @tprouvot I am looking for this everywhere, but it seems not to be yet released in main, right? Do you have an ETA?

**Comment by tprouvot** [comment]
Hi @Damecek,
You're right this is only released on beta at the moment.
I'll probably release this version in July
