### ISSUE TITLE
Salesforce inspector without connected app explanation

### ISSUE THREAD

**Issue by ashrafbaker** [tprouvot/Salesforce-Inspector-reloaded#172]
Hi,
In an action of security audit, we have users that uses Inspector to view hidden information in Salesforce.
In Salesforce we have shield to view the ELFs enabled, and we would like to know how Inspector connects and opens a session, if it is via connected app (may be not as we didn't create one)? or does it do API calls to Salesforce?
Any help would be welcomed as we adore your app and it is a must have for any Salesforce user nowadays.
Kind regards

**Comment by tprouvot** [comment]
Hi @ashrafbaker ! 
Salesforce Inspector Reloaded by default, uses the session Id generated by Salesforce and stored in the cookies. 
The extension works with API callouts.

Now if your need is to control who can access Salesforce Inspector Reloaded (and potentially other extensions as well) you have to setup API restriction and disable API access. Make sure to test all your processes after disabling API. 

Once you've done that, you can configure a connected app and choose which profile pset access to inspector (available in the 'how ton section of the documentation)

**Comment by tprouvot** [comment]
Hi @ashrafbaker,
Are you ok with the answer ? 
I'll close the issue, if you have any question feel free to add a comment and I'll re-open it !
