### ISSUE TITLE
Publish the extension in Edge Store

### ISSUE THREAD

**Issue by akingumusel** [tprouvot/Salesforce-Inspector-reloaded#177]
**Is your feature request related to a problem? Please describe.**
The extension is currently only available on Chrome and Firefox browsers. As company policy, the Chrome extension store is blocked. 

**Describe the solution you'd like**
Make the extension available in Edge Store

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by tprouvot** [comment]
Hi @akingumusel,
The extension is reviewed by Microsoft teams, should be available in next 7 days.

**Comment by akingumusel** [comment]
Thanks for the quick resolution @tprouvot.

**Comment by tprouvot** [comment]
Hi @akingumusel,

The extension is live !

https://microsoftedge.microsoft.com/addons/detail/salesforce-inspector-relo/noclfopoifgfgnflgkakofglfeeambpd
