### ISSUE TITLE
Extension preserves old domain after it was changed

### ISSUE THREAD

**Issue by oleg-mastriukov** [tprouvot/Salesforce-Inspector-reloaded#186]
**Describe the bug**
If you log in to the org, the extension saves its domain somewhere in the internal memory. For example, if you open a Data Export feature, the current org's domain is in the URL.
If in your org you go to Setup - Custom Domain, change it, and apply changes to the org, the extension still uses the old domain for all its features. If you open the Data Export, it won't work because there's an old domain in the URL

**Comment by tprouvot** [comment]
Hi @oleg-mastriukov,
I think if you reload without cache it should solve the problem.
Anyway create a feature to detect the domain change would be overkill since it occurs very rarely.
