### ISSUE TITLE
Export data: suggested objects not fully shown

### ISSUE THREAD

**Issue by saschastier** [tprouvot/Salesforce-Inspector-reloaded#194]
Hi looks like there is no way to expand the list of suggested objects.  It shows only whatever fits in one line.

Thanks for your hard work.
cheers,
sascha

![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/70657868/7a922830-0081-47b8-9fdb-7a1ab62211b9)

**Comment by tprouvot** [comment]
Hi @saschastier,
Have you tried the dropdown button ? 

![2023-11-02_14-34-53 (1)](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/129da1a0-0c76-4a38-9694-3aea1b4cc0f5)
