### ISSUE TITLE
EDGE - [data-import] - Copy (Excel format) is not in excel format but a CSV format

### ISSUE THREAD

**Issue by BTJason** [tprouvot/Salesforce-Inspector-reloaded#195]
**Describe the bug**
When performing a data import and then looking to copy the results of said import. The Copy (Excel format)  button does not copy to an excel format but to a CSV format.

**To Reproduce**
1. Select data import
2. run an import of some kind
3. when processing is completed click the The Copy (Excel format)  button
4. paste to excel

**Expected behavior**
data should be copied to columns and rows  format and not in a CSV format
**Screenshots**

**Desktop (please complete the following information):**
 -windows 11
 - Browser Edge
 - Version Version 118.0.2088.76

**Additional context**

**Comment by tprouvot** [comment]
Hi @BTJason, 
I'm not able to reproduce the behaviour you describe.

It may come from excel configuration on your computer, have you tried with google sheet ?

![2023-11-02_17-01-40 (1)](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/b7fb912d-187b-4adf-b55d-9e68b1c61239)

**Comment by BTJason** [comment]
Very weird.  It does not work in excel but does work in google spreadsheet.  i created a quick video to demo.  i dont know what settings because this is the only time i have experienced this



inspector (vidyard.com)<https://bt.hubs.vidyard.com/watch/2nm18iq8JKjhecsZD8V9G2?>






Jason Rojas

Salesforce Administrator

Need to schedule a meeting, click here<https://calendly.com/jason-rojas-1> to see my availability.


 [cid:58690f5e-c882-49dc-8427-d872b7c685fe]



Baker Tilly US, LLP

T:+1  703-923-8015

8219 Leesburg Pike, Suite 800, Tysons, VA 22182 USA

***@***.*** | bakertilly.com<http://www.bakertilly.com/>

[cid:9fd3c363-cef5-452a-a788-7250d5a590f1]<https://www.facebook.com/BakerTillyCareers/>[cid:1ccfb78d-71b4-4f0f-ae8e-038d4d9ac22d]<https://twitter.com/bakertillyus>[cid:1d1462c3-b8bd-463b-95f6-5cc3675170c7]<https://www.linkedin.com/company/baker-tilly-virchow-krause-llp>[cid:51d302a4-f00b-4bfd-acb2-121abd4e62a9]<https://www.youtube.com/user/BakerTillyUS>

Baker Tilly US, LLP trading as Baker Tilly is a member of the global network of Baker Tilly International Ltd., the members of which are separate and independent legal entities.

________________________________

**Comment by BTJason** [comment]
My excel is working now.  Thanks for looking into this.  good ol Microsoft products


Jason Rojas

Salesforce Administrator

Need to schedule a meeting, click here<https://calendly.com/jason-rojas-1> to see my availability.


 [cid:2d2cef29-d87d-497b-9a3a-b38648724782]



Baker Tilly US, LLP

T:+1  703-923-8015

8219 Leesburg Pike, Suite 800, Tysons, VA 22182 USA

***@***.*** | bakertilly.com<http://www.bakertilly.com/>

[cid:4ea445c4-f9a2-43bf-b854-e7b28e0c2cc9]<https://www.facebook.com/BakerTillyCareers/>[cid:5bf61974-0e41-4898-88e1-7209be490255]<https://twitter.com/bakertillyus>[cid:8f562772-60d6-4111-b525-b44c2075093a]<https://www.linkedin.com/company/baker-tilly-virchow-krause-llp>[cid:d118591a-09cc-406c-b119-19a108893c7c]<https://www.youtube.com/user/BakerTillyUS>

Baker Tilly US, LLP trading as Baker Tilly is a member of the global network of Baker Tilly International Ltd., the members of which are separate and independent legal entities.

________________________________

**Comment by tprouvot** [comment]
Happy to see that your issues is solved, thanks for using Reloaded!

**Comment by BTJason** [comment]
Thank you for developing its the Swiss army knife that I use daily

Jason Rojas

Salesforce Administrator

Need to schedule a meeting, click here<https://calendly.com/jason-rojas-1> to see my availability.


 [cid:23edcc45-f367-41fa-aaac-b7bc2f6425c5]



Baker Tilly US, LLP

T:+1  703-923-8015

8219 Leesburg Pike, Suite 800, Tysons, VA 22182 USA

***@***.*** | bakertilly.com<http://www.bakertilly.com/>

[cid:ea9305c8-9f07-4560-bf42-3df73d3cdc25]<https://www.facebook.com/BakerTillyCareers/>[cid:17ce3a15-508d-4d8e-8c6a-84c9b7b809a8]<https://twitter.com/bakertillyus>[cid:d9ccdbe9-d067-493c-868f-f31a8140e8b8]<https://www.linkedin.com/company/baker-tilly-virchow-krause-llp>[cid:b1057ee6-33e1-43d9-a859-78ea2e6ecd79]<https://www.youtube.com/user/BakerTillyUS>

Baker Tilly US, LLP trading as Baker Tilly is a member of the global network of Baker Tilly International Ltd., the members of which are separate and independent legal entities.

________________________________
