### ISSUE TITLE
Display API Name on the UI page layout (see screen shot)

### ISSUE THREAD

**Issue by Johno72** [tprouvot/Salesforce-Inspector-reloaded#196]
**Describe the solution you'd like**
As a System Admin, I want to open the Salesforce Inspector Reloaded, then click a link or button to "**display the API name**" next to or below the field label displayed on the page. 

As an added bonus, if I click on the API name displayed on the page it should highlights the full API name to make copy / paste simple. This behaviour is the same as Salesforce Inspector Reloaded > click the "Show All Data" button > using the mouse, click on any text in the table. The data auto highlights the text clicked.

As an additional added bonus, add an icon next to the API Name e.g. ![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/30250889/16728e58-f271-444f-ab60-72f4726e2295) that allows the user to click and go to Setup> Object field.

**Describe alternatives you've considered**
I use another Chrome extension called "Salesforce Show API Name". However much like the orginal Salesforce Inspector it is no longer being maintained. 
[Salesforce Show API Name](https://github.com/ChenZaichuang/salesforce_show_api_name)

By adding this feature we can consolidate Salesforce helper chrome apps and look forward to additional features and support over time.

**Additional context**

**Example screen shot**
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/30250889/e5b74646-ec5c-46b8-84cb-fd251e988592)

**Comment by MD931** [comment]
Hi @tprouvot 

Can you assign me to this issue? It corresponds to this PR https://github.com/tprouvot/Salesforce-Inspector-reloaded/pull/202. Thank you! 😄

**Comment by tprouvot** [comment]
Will be available in the next version !

**Comment by Johno72** [comment]
Hi @tprouvot and @MD931. I just wanted to say thank you both for adding my feature enhancement request. I have now uninstalled the old API Name Chrome Add-on since this replaces it! Love it, thank you both.

Cheers,
John

**Comment by tprouvot** [comment]
Hi @Johno72,
Thanks for your feedback, glad to hear that you enjoyed the feature, well done @MD931 👏
Reloaded to rule them all ! 🚀
