### ISSUE TITLE
[show-all-data] Customise  header of REST call

### ISSUE THREAD

**Issue by SfdxDieter** [tprouvot/Salesforce-Inspector-reloaded#198]
Salesforce changed default behavior of REST call if Cases are changed. If changes are done in Inspector there is not send the Sforce-Auto-Assign Value in the header of the REST-Call. So Assigement Rules are executed every time. But normaly before the assignement rules where not firered every time. 
So the Inspector should send  Sforce-Auto-Assign with value FALSE or be configure able to switch it on/off.

https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/headers_autoassign.htm
https://help.salesforce.com/s/articleView?id=000390059&type=1

**Comment by SfdxDieter** [comment]
In inspect.js line 150 it would be 
sfConn.rest(recordUrl, { method: "PATCH", body: record, headers: {"Sforce-Auto-Assign" : false} }).then(() => {

**Comment by tprouvot** [comment]
Hi @SfdxDieter ,

Good catch 👏  ! 
I'll probably implement a variable in localStorage to let users define custom headers in create and update rest callout from show all data view.
I'll post updates here !

**Comment by tprouvot** [comment]
Hi @SfdxDieter ,

You can test the header customisation by checking out [this branch](https://github.com/tprouvot/Salesforce-Inspector-reloaded/tree/feature/addCustomHeaderForCreateUpdateShowAllData) locally and follow this [how to](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/feature/addCustomHeaderForCreateUpdateShowAllData/docs/how-to.md#enable-summary-view-of-permissionset--permissionsetgroups-from-shortcut-tab).

I'll test this does not bring regressions on the create updates for a while locally, if everything is good I'll merge it into releaseCandidate (next release branch).

Let me know if you need assistance !

**Comment by SfdxDieter** [comment]
After the first test, where it does not worked, I get "Uncaught SyntaxError: Unexpected token 'export'" in the plugin an it does not start any more.

**Comment by SfdxDieter** [comment]
Currently I see a lot off errors. I can see that the parameter is used. But it does not work as exspected. I will check it.
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/74535684/292bfbd8-e3be-4e53-9d8c-5658efa6342a)

**Comment by tprouvot** [comment]
@SfdxDieter  
Have you disabled the extension from the chrome web store after installing the legacy version ?

**Comment by SfdxDieter** [comment]
Please change line 36 to
    this.headerCallout = JSON.parse( localStorage.getItem("createUpdateRestCalloutHeaders") ? localStorage.getItem("createUpdateRestCalloutHeaders") : "{}");
then it works. (I cann't push to git)

I get 2 kind of errors in the plugin
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `AllDataSelection`. See https://fb.me/react-warning-keys for more information. in div (created by AllDataSelection) in AllDataSelection (created by AllDataBoxSObject) in div (created by AllDataBoxSObject) in AllDataBoxSObject (created by AllDataBox) in div (created by AllDataBox) in AllDataBox (created by App) in div (created by App) in div (created by App) in App
and 
Uncaught SyntaxError: Unexpected token 'export'

**Comment by SfdxDieter** [comment]
When using npm run chrome-dev-build the manifest.json is changed. The links.js is added 
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/74535684/e75ee34e-7f08-435a-9094-93bd907cecd7)

if I remove after the build the links.js again and upload it to chrome the token export error does not appear

**Comment by tprouvot** [comment]
Adding a new option to set the custom header
<img width="846" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/fba23a19-0b11-4275-b4d9-52e9e6ac1bd9">

**Comment by tprouvot** [comment]
Will be available in beta version probably next week
