### ISSUE TITLE
New flow layout is blocked by SFinspector placements

### ISSUE THREAD

**Issue by AdminJensen** [tprouvot/Salesforce-Inspector-reloaded#200]
Simply open the Salesforce flow builder, open an element, and you will see you cannot close the element again due to the small Arrow that opens up Salesforce inspector.

**Screenshots**
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/95715450/8d187210-b84d-445c-933e-f23867f553e7)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version:  Latest

**Additional context**

**Comment by tprouvot** [comment]
Hi @AdminJensen ,
This needs is already describe in this issue: 
https://github.com/tprouvot/Salesforce-Inspector-reloaded/issues/145

I'll close this one since it's a duplicate
