### ISSUE TITLE
[popup] Ability to show / hide buttons

### ISSUE THREAD

**Issue by tprouvot** [tprouvot/Salesforce-Inspector-reloaded#203]
**Is your feature request related to a problem? Please describe.**
Since the number of buttons is increasing and their usage depends on the user's habits, it could be great to be able to hide some of them.

Personaly speaking, I'm not using "Download Metadata" or "Setup Home"

Before:
<img width="277" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/629708cc-a94d-4ac9-bfed-f9eabcb286d9">

After:
<img width="277" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/7bf28fe0-9f4d-41fa-8095-c201bd2fc186">

**Describe the solution you'd like**
We would use localStorage to define if a button must be hidden or not.

**Comment by toly11** [comment]
@tprouvot, Is there a plan to add a settings page?

**Comment by tprouvot** [comment]
@toly11 Yes @pietromartino started to implement it, however since I released the beta version I won't add more functionalities but bugfixes to the 1.21

It will be for the 1.22 !

**Comment by kaustubhdapurkar** [comment]
Hi @tprouvot , I would like to implement this, to start, how do you want the UI to look like on the options page? Should it be a dropdown which when clicked opens a list of checkboxes, one for each button and the user can select the needed checkboxes and close/save, or something else like below?

![{547716B4-5297-4FE0-A57D-4A30905AD420}](https://github.com/user-attachments/assets/89f19c82-6ce4-404e-8033-a4ce5d82d2c0)
![{FA04010E-D254-4160-B06E-C98FEC436C0C}](https://github.com/user-attachments/assets/d1c22120-1c16-4923-9da1-807af84030c9)
![{98641F07-1783-4ED5-B85B-3D8D3A1D86E0}](https://github.com/user-attachments/assets/18e0fc95-8efc-4129-babb-7af0e475d87f)

**Comment by tprouvot** [comment]
Hi @kaustubhdapurkar ,

It is already implemented in the releaseCandidate branch
