### ISSUE TITLE
User Selection not displaying user information

### ISSUE THREAD

**Issue by mackarovSF** [tprouvot/Salesforce-Inspector-reloaded#211]
When using Salesforce Inspector Reloaded and trying to view a specific user, the drop down shows users matching the search. However, when selecting the desired user, the usual user information and buttons to login, view details, etc., doesn't appear and it shows "No user details available". 

**To Reproduce**
1. Open Salesforce Inspector Reloaded in Salesforce org. 
2. Click on User tab
3. Search for an active user.
4. Select the user.

**Expected behavior**
I expected to be able to view the user details and buttons to login as the user, view user details, view permission sets, and view permission set groups.

**Screenshots**
No screenshots because it would show user PII.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 119.0.6045.124 (Official Build) (64-bit)

**Additional context**
This started happening today (11/8/2023). I have uninstalled the extension and reinstalled the extension. I updated Chrome from an older version to the up to date version. Other features work as expected.

**Comment by tprouvot** [comment]
Hi @mackarovSF,

Could you check chrome dev console and see if there's any error ?
Thanks

**Comment by mackarovSF** [comment]
@tprouvot, sure! Here's the dev console error:

```
popup.js:586 Unable to query user details with: {"compositeRequest":[{"method":"GET","url":"/services/data/v59.0/query/?q=SELECT%20Id%2C%20Name%2C%20Email%2C%20Username%2C%20UserRole.Name%2C%20Alias%2C%20LocaleSidKey%2C%20LanguageLocaleKey%2C%20IsActive%2C%20FederationIdentifier%2C%20ProfileId%2C%20Profile.Name%2C%20ContactId%2C%20IsPortalEnabled%20FROM%20User%20WHERE%20Id%3D'0051300000BKI2JAAX'%20LIMIT%201","referenceId":"fullData"},{"method":"GET","url":"/services/data/v59.0/query/?q=SELECT%20Id%2C%20Name%2C%20Email%2C%20Username%2C%20UserRole.Name%2C%20Alias%2C%20LocaleSidKey%2C%20LanguageLocaleKey%2C%20IsActive%2C%20FederationIdentifier%2C%20ContactId%2C%20IsPortalEnabled%20FROM%20User%20WHERE%20Id%3D'0051300000BKI2JAAX'%20LIMIT%201","referenceId":"minimalData"}]}. TypeError: Cannot read properties of undefined (reading 'body')
    at AllDataBoxUsers.querySelectedUserDetails (popup.js:575:93)
    at async AllDataBoxUsers.onDataSelect (popup.js:542:7)
querySelectedUserDetails @ popup.js:586
await in querySelectedUserDetails (async)
onDataSelect @ popup.js:542
await in onDataSelect (async)
updateAllDataInput @ popup.js:1380
onResultClick @ popup.js:1519
onClick @ popup.js:1580
ReactErrorUtils.invokeGuardedCallback @ react-dom.js:8972
executeDispatch @ react-dom.js:2979
executeDispatchesInOrder @ react-dom.js:3002
executeDispatchesAndRelease @ react-dom.js:2431
executeDispatchesAndReleaseTopLevel @ react-dom.js:2442
forEachAccumulated @ react-dom.js:15401
processEventQueue @ react-dom.js:2618
runEventQueueInBatch @ react-dom.js:8996
handleTopLevel @ react-dom.js:9007
handleTopLevelImpl @ react-dom.js:9084
perform @ react-dom.js:14702
batchedUpdates @ react-dom.js:8760
batchedUpdates @ react-dom.js:12815
dispatchEvent @ react-dom.js:9159
app.css:1 
        
        
       GET https://[mydomain_redacted]--tradeshow.sandbox.file.force.com/file-asset/Default_User_Profile_Banner_Workwe2?v=1 404 (Not Found)
```

**Comment by RebbePod** [comment]
Same issue here starting today

**Comment by tprouvot** [comment]
Hi @mackarovSF @RebbePod ,
I coud reproduce the issue on a trailhead org, I'll fix this and send an update to chrome right away.
Should be available in a day or two, during this time you can download the[ previous version](https://github.com/tprouvot/Salesforce-Inspector-reloaded/archive/refs/tags/1.19.zip) and [install it locally ](https://github.com/tprouvot/Salesforce-Inspector-reloaded#local-installation)

Apologies for the inconvenience I'm really sorry

**Comment by mackarovSF** [comment]
@tprouvot Thank you so much! I installed the reloaded version about two weeks ago and love it. You rock!

**Comment by tprouvot** [comment]
@mackarovSF @RebbePod if you are on a sandbox you can also enable digital experience and it will solve the issue

<img width="1180" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/5fbd6773-169e-4d81-a80c-3314e73fd8da">

 Be careful this will enable my domain, use this option at your own risks 😄

**Comment by tprouvot** [comment]
The fix is waiting for review on the Chrome web store, it should be ok tomorrow 🤞

**Comment by RebbePod** [comment]
Thank you

**Comment by tprouvot** [comment]
@RebbePod  @mackarovSF 
Hi guys !
The fixes has been released, could you check if everything is ok for you ?

**Comment by RebbePod** [comment]
Same here. Thank you!
