### ISSUE TITLE
[data-export] Add a formatter for SOQL Queries

### ISSUE THREAD

**Issue by jbatt08** [tprouvot/Salesforce-Inspector-reloaded#216]
**Is your feature request related to a problem? Please describe.**
Sometimes my SOQL queries are poorly formatted and difficult to read.

**Describe the solution you'd like**
Add a button to format SOQL queries - something like what this page does: http://codegen.keweme.com/SOQL

**Comment by akalatksy** [comment]
http://codegen.keweme.com/SOQL is quite a bad example of formatting, imho.

**Comment by tprouvot** [comment]
Hi @jbatt08,
I'm closing this issue, the follow up will be done in #359
