### ISSUE TITLE
Popup button not show on Firefox

### ISSUE THREAD

**Issue by zhanglhz** [tprouvot/Salesforce-Inspector-reloaded#217]
**Make sure to read the troubleshooting section before creating an issue**

- [ ] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/8307604/1a7e79ad-954c-46a1-9926-a29a0712ab37)

**Desktop (please complete the following information):**
 - OS: [Windows 11] & [Manjaro Linux 23.1.0 Vulcan]
 - Browser [firefox]
 - Version [119.0.1]

**Additional context**
I found that Salesforce-Inspector-reloaded popup button can not show on Firefox. Please see the screenshot.

I upgraded to latest version of extension and find the problem, so I uninstall it and clear the cookie, then I reinstall  "Salesforce-Inspector-reloaded", the problem still exists.

**Comment by tprouvot** [comment]
Hi @zhanglhz, 
I could reproduce the behaviour, I've submitted a new version for firefox 1.202 which should be available soon.

**Comment by tprouvot** [comment]
Hi @zhanglhz the new version is available on firefox store

**Comment by zhanglhz** [comment]
Hi @tprouvot, I updated to 1.202. The problem has been fixed.

I'll close the issue.
