### ISSUE TITLE
Make Org Id visible from the SF Inspector Panel

### ISSUE THREAD

**Issue by TimFroger** [tprouvot/Salesforce-Inspector-reloaded#225]
**Context**
We often have to share the Org Id to Salesforce Support (or ISV Support) which means going to Setup > Company Information (or using the shortcut tab).
However, it could be even faster if we have it displayed directly on the SF Inspector Panel

**Requirement**
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/121184443/aaf09341-cc0c-4254-9776-742e028653be)
Having the Org ID next to the instance name would be perfect

**Comment by tprouvot** [comment]
Hi @TimFroger ! 
Long time no see 😄 

We way have something for you, a colleague started to develop a new popup tab with info from the org, instance, and next release / incident.
I'll catch him to see if we can use his work 👍

**Comment by tprouvot** [comment]
New org tab will be available in next release, currently without the copy Id functionality but can be added in the future
