### ISSUE TITLE
Inspector does not work on Alibaba cloud domain

### ISSUE THREAD

**Issue by lcee-info** [tprouvot/Salesforce-Inspector-reloaded#232]
![WechatIMG54](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/22517059/2b33fc08-23cc-4834-ab32-3b0f77d1d484)

Hi,
As Salesforce China Database is on Ali Cloud ,the Salesforce Domain does not included in the Inspector configured domains,
now we can not user Salesforce Inspector with our new Salesforce org.
It would be very thankful if you can have any idea or workaround to resolve our problem.

Best regards!

**Comment by tprouvot** [comment]
Hi @lcee-info 
There is already a PR to allow Inspector Reloaded to run on Alibaba cloud, I'm missing someone who could grant me access to an empty scratch org in order to perform some tests.

Would you be able to do that ?

**Comment by lcee-info** [comment]
> Hi @lcee-info There is already a [PR](https://github.com/tprouvot/Salesforce-Inspector-reloaded/pull/141) to allow Inspector Reloaded to run on Alibaba cloud, I'm missing someone who could grant me access to an empty scratch org in order to perform some tests.
> 
> Would you be able to do that ?
