### ISSUE TITLE
With new Inspector, when I'm in 'Show All Data' mode, and editing a field, I get the "Error saving record" error.   

### ISSUE THREAD

**Issue by lrobbinsagloan** [tprouvot/Salesforce-Inspector-reloaded#240]
**Make sure to read the troubleshooting section before creating an issue**

- [ ] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, firefox, edge]
 - Version [e.g. 1.20]

**Additional context**

**Comment by tprouvot** [comment]
Hi @lrobbinsagloan ,

Could you fill the required sections of the issue and add screenshot?
Thanks

**Comment by lrobbinsagloan** [comment]
Describe the bug
When Editing in Inspector, the field does not update.  This happens to me, and my profile is Admin.  Other Admins are not encountering this error,  as they are able to  make updates and SAVE the record.  

To Reproduce
Steps to reproduce the behavior:

Go to Inspector
Click on 'Show All Data'
Locate / Search on a field that I want to update.  
In the Value field, update value to a blank.
Click SAVE.
Error is presented.  The error is attached.


Expected behavior
Field should update to the value I entered.   

Screenshots
Attached.

Desktop (please complete the following information):

Browser  chrome
Version 1.20.1

**Comment by tprouvot** [comment]
Hi @lrobbinsagloan 
On which object are you trying to edit the record ?

There's no screenshot or error attached, please check again.

**Comment by tprouvot** [comment]
@lrobbinsagloan again on which object are you trying to perform the update ?
Please add more details (video of your screen with all the process).

My guess is that you are trying to update a field that is not updatable or you don't have the rights on it.
If you are admin, try to update it from UI or apex, if you are facing the same issue it is not a Salesforce inspector issue.

If you are able to perform the updates outside inspector let me know and i will reopen the issue

**Comment by lrobbinsagloan** [comment]
Hi, appreciate the feedback.  I wasn't able to update the field via Inspector, but a co-worker who is an Admin was able to update the field via Inspector.   I am comparing / contrasting the permission sets between myself and the other Admin, and don't see anything obvious that stops me from updating via Inspector.  Are you aware of any specific permission set that would cause this?
