### ISSUE TITLE
[popup] Add "Enable debug logs" button on user tab

### ISSUE THREAD

**Issue by tprouvot** [tprouvot/Salesforce-Inspector-reloaded#245]
**Is your feature request related to a problem? Please describe.**
It would be great if we could enable debug logs for a particular user directly from the User tab

**Describe the solution you'd like**
<img width="279" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/bf389978-25b6-4b7e-8f62-267ba07d2e62">

This would create a TraceFlag record with FINEST logs for all and for 30 min by default.
We would add localStorage options to customize duration and log levels

**Comment by tprouvot** [comment]
@AntoineLeleu-Salesforce The floor is yours 🚀

**Comment by KamilGadawski** [comment]
@tprouvot would it be a good solution if, when the user clicks the Debug button, it takes them to the configured Delug Logs as in the screenshot below?

![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/28691476/c01eee12-5fbd-421d-af74-d8b80b8302aa)

**Comment by tprouvot** [comment]
@KamilGadawski we could have dont this, but we choose to create a trace flag straight away.
@AntoineLeleu-Salesforce is currently implementing this 🚀
