### ISSUE TITLE
[Alibaba Cloud support]

### ISSUE THREAD

**Issue by mitxi21** [tprouvot/Salesforce-Inspector-reloaded#248]
Recenlty Salesforce opened new servers in China. The servers used there are not supported in the current Site Access settings: lightning.sfcrmapps.cn

Could the server lightning.sfcrmapps.cn be added to the list?

Or maybe can the list be edited? This will allow to modify it in the future if new servers are added without releasing new extensions versions.

Thanks,
Mitch

**Comment by tprouvot** [comment]
Hi @mitxi21 
The Alibaba Cloud domain [should be added](https://github.com/tprouvot/Salesforce-Inspector-reloaded/pull/141), would you be able to create me some sandbox / scratch org access so that I can test it ?

**Comment by mitxi21** [comment]
Hi @tprouvot,

thanks for the prompt answer. I have prepared a sandbox where the extension can be tested. How I send you the credentials? Email?

I'm a developer too so I can help doing the changes if you don't have the time. I've never played with chrome extensions but, well, there should be a first time :)

Just let me know.

Thanks,
Mitch

**Comment by tprouvot** [comment]
Hi @mitxi21,
Yes by email is perfect ! 
The PR is almost ready to merge, I just have some small updates to do but if you want to contribute you are more than welcome!

**Comment by mitxi21** [comment]
Hi @tprouvot,

great, do you mind sharing an email address? I can't find any in your github profile :/

Thanks!
Mitch

**Comment by tprouvot** [comment]
@mitxi21 I thought it was available on github, can you add me on Linkedin ? I'll give it to you

**Comment by mitxi21** [comment]
Sure, I have sent my invite.

**Comment by tprouvot** [comment]
Hi @mitxi21 ,
I could test the feature and it works well, the merge has been made on releaseCandidate (so you can checkout locally and test it)
Unfortunately, a new feature from the org tab does not work on Alibaba Cloud since the Chinese instances are not refered in 
https://status.salesforce.com/ do you know if there's an alternate website to check for instance status in Alibaba Cloud ?

**Comment by mitxi21** [comment]
Hi,

Thanks @tprouvot I will test it. I don't think there's a status instance website released yet but I hope it will be in the future.

**Comment by mitxi21** [comment]
Hi @tprouvot,

I checked locally and it works perfectly, thanks!
