### ISSUE TITLE
[data-export] Better handling of long queries

### ISSUE THREAD

**Issue by natel628** [tprouvot/Salesforce-Inspector-reloaded#250]
**Is your feature request related to a problem? Please describe.**
when doing a longer query with many records with an IN operator it doesn't work
 **Describe the solution you'd like**
write longer queries, currently I have to use workbench
**Describe alternatives you've considered**
use workbench
**Additional context**

**Comment by tprouvot** [comment]
Hi @natel628,
Please add an example

**Comment by tprouvot** [comment]
@natel628 without details I won't be able to help you, please let me know if I you can provide some.

**Comment by natel628** [comment]
Select name from contact where ID in (<list 1,000 IDs>) and it returns "null" 

I can do a list of 500 and it works fine. I just tried with workbench using 2,000 and it worked fine.

**Comment by LexerEP** [comment]
I often have the same problem, normally up to 20000 characters should be possible. But it only works up to 14253 characters.
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/69196690/2eb8772e-1c7b-4bcd-9a0d-374571af4c5a)

**Comment by prem-k-r** [comment]
Added automatic splitting and merging of large SOQL IN clauses. #1238
