### ISSUE TITLE
Copy paste resetting the "Action" picklist

### ISSUE THREAD

**Issue by Mart-User** [tprouvot/Salesforce-Inspector-reloaded#252]
In previous versions,

when I used the "Copy (Excel format)" feature from the "Data Export"
and paste the result on "Data Import", the "Action" picklist didn't change

In recent version (1.20.1) the picklist is reset to the "Insert" mode

**Comment by tprouvot** [comment]
Hi @Mart-User,
It does indeed, the goal is to automatically fill some data import inputs.
I would suggest to paste and then update the fields.

Since you did not used the issue template, some information are missing,  can I have more info about the the dml you are trying to perform and the object ?
Maybe a gif from a screen recording ?

**Comment by Mart-User** [comment]
My use case:

I have a log object that I often delete the records based on a saved query
Because In my org I have several errors and I have to do that to look at the data more precisely

So every day I go to the "Data Export", get my saved query, retrieve data
Then I import the data in "Data Import" to do a delete

Since I know I would use the delete function, I was used to already select the "Delete" action
And the paste the query from "Data Export", that would already select the related SObject
but now I have to paste and then re-select delete

The simple step-by-step would be:
*open the "Data Export"
*do a simple select query
*use the "Copy (to Excel)"
*open the "Data Import"
*select "Delete" action on "Data Import"
*paste your query
*Action picklist would reset to "Insert" (even having an Id in the pasted query)

I can't record it since some data is confidential.

I know it is a minor thing but makes a whole difference for me,
also I don't see how would be beneficial resetting the Action value to "Insert" in this case

But if it won't be reviewed, no problem.

**Comment by tprouvot** [comment]
Ok I see, are you aware of the "Delete records" functionality ?
https://github.com/tprouvot/Salesforce-Inspector-reloaded/issues/134

I think it fits your need perfectly 🤌 

Other suggestion would be to schedule the deletion using the [purge-sobject](https://github.com/tprouvot/purge-sobject) framework

Anyway I could detect when manual action is performed and not override it on paste but in your case I think 'Delete functionality' would save you some clics

**Comment by Mart-User** [comment]
I tried the "Delete records" feature but if there are several records (like 40k, which is my case) the tab opens blank, with fewer records it works.
