### ISSUE TITLE
[data-export] Delete button does not check for 'toolingApi' parameter

### ISSUE THREAD

**Issue by tprouvot** [tprouvot/Salesforce-Inspector-reloaded#254]
**Make sure to read the troubleshooting section before creating an issue**

- [ ] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.

**Describe the bug**
From data export page, when trying to delete records queried with tooling api, the api is not automatically selected.

**To Reproduce**
1. Go to 'data-export'
2. Query `SELECT Id from TraceFlag`
3. Click 'Delete Records' buttons
4. Deletion is not possible since we should use Tooling api and not Entreprise api

<img width="1047" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/a7dba01c-6a9e-4b29-949f-b2abaaeea1a2">

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser chrome
 - Version 1.21

**Comment by tprouvot** [comment]
Hi @ogomezba ! 
Just for information, there was a rework on the API selection for supporting CMDT upsert, maybe it's a regression.
Let me know if you want to take a look at it, otherwise I'll address it.

**Comment by ogomezba** [comment]
Hi @tprouvot! Yes, I was going to open an issue for this! I want to work on it indeed, thank you for creating it!
