### ISSUE TITLE
sfcmdk: enable compatibility

### ISSUE THREAD

**Issue by hansds** [tprouvot/Salesforce-Inspector-reloaded#257]
**Is your feature request related to a problem? Please describe.**
[sfcmdk](https://github.com/hansds/sfcmdk) currently opens the old Salesforce Inspector to allow users to easily inspect a record from the command palette. We would love to migrate this to this reloaded extension.

**Describe the solution you'd like**
We would need to whitelist sfcmdk in this extension:

```json
{
  // …
  "web_accessible_resources": [
    {
      "resources": ["inspect.html"],
      "extension_ids": ["bmgfnhdlojiieehhdlfmngfhnnhhgeml"]
    }
  ]
  // …
}
```

**Describe alternatives you've considered**
I don't see an alternative from our side. Chrome manifests now err on the side of closed security by default, but this does cause it to block our extension calling the salesforce inspector.

**Additional context**
How it looks in sfcmdk - we just open the `inspect.html` and insert the correct record id and sobject type:
<img width="665" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/24360848/82663ce1-6910-4afb-bb20-51fad45e8a2a">
<img width="691" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/24360848/7b211a76-edce-4fdd-ad01-7db89c0d9c76">

**Comment by tprouvot** [comment]
Hi @hansds, 
Thanks for your interest in integrating with reloaded ! 

To be honest, because of trust and security concerns I'm not very comfortable with integrating with another extension that I do not owe.
That being said, I Can see that there is similar functionalities, if you have suggestion on new feature, PR are welcome!

**Comment by hansds** [comment]
Hey @tprouvot - thanks for the feedback! I definitely appreciate your concerns. I'll look into forking or integrating the inspect functionality into our extension some other way. Thanks anyway!
