### ISSUE TITLE
[flow-scrollability] Checkbox is not displayed on non sandboxes environments

### ISSUE THREAD

**Issue by tprouvot** [tprouvot/Salesforce-Inspector-reloaded#258]
**Make sure to read the troubleshooting section before creating an issue**

- [x] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.

**Describe the bug**
On developer edition, sdo or prod env, the input checkbox is not diplayed

**Expected behavior**
Checkbox should be also displayed

**Screenshots**
<img width="1432" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/c624a3eb-50c1-4c7c-8c7e-5d9a92136bcb">

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser chrome
 - Version 1.21

**Additional context**
Relates to #40

**Comment by tprouvot** [comment]
Hi @skrissi, 
Happy new year ! 
Would you like to check this one or should I address it?

**Comment by skrissi** [comment]
Hi @tprouvot  I will try to check this

**Comment by tprouvot** [comment]
> Hi @tprouvot  I will try to check this

Awesome thank you!
