### ISSUE TITLE
[feat] Import : format relations as expected on paste

### ISSUE THREAD

**Issue by tprouvot** [tprouvot/Salesforce-Inspector-reloaded#26]
When exporting data from inspector, the format is "MaskSObject__r.APIName__c"
<img width="698" alt="image" src="https://user-images.githubusercontent.com/35368290/208933202-6128c639-6c83-438d-a70c-7068b5a9e22a.png">

But the expected format is : "MaskSObject__r:MaskSObject__c:APIName__c"

Either update the expected format or format the input as expected on the paste

**Comment by dufoli** [comment]
hello, this feature is not useless. If we do an upsert we can use external id to of linked object to create the link.
Example, I have an Account with externalID__c  field (externalID checked on setup) then I can Import a contact with:
Contact Name, Account:Account:ExternalID__c
Olivier; MyAccountExternalId

then SF on import will find the link to account based on it and provide AccountId on Contact.

**Comment by tprouvot** [comment]
Hi @dufoli ,
OK I re-open this issue 👍

**Comment by dufoli** [comment]
anyway great tool and happy to see it back. I can try to provice a PR for that.

**Comment by dufoli** [comment]
I do not know how to test So I code it blindly

**Comment by tprouvot** [comment]
Hi @dufoli,
I would be more than happy to review your PR! 
About the approach, I think it would be better to update the expected format on import side since those convention ":" does not exist in Salesforce and we are used to see the "." for separating the related object. 

What do you think?

**Comment by dufoli** [comment]
'thats whats i have done
