### ISSUE TITLE
Bigger invoke button

### ISSUE THREAD

**Issue by Astisme** [tprouvot/Salesforce-Inspector-reloaded#270]
# Current issue
<img width="1020" alt="Screenshot 2024-01-09 162248" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/96465880/b3a871f5-dad1-4576-bb02-2831f5faffbc">

The arrow button used to invoke Salesforce Inspector is too small and it requires the user to be very careful in order to launch the popup.

Most of the times, I find myself unable to open the popup because my mouse only goes on the scrollbar (which is why I've installed an extension to remove all scrollbars).

# Proposed solution A
Set bigger sizes for the button.

# Proposed solution B
Move the button to the left so that it does not interfere with the scrollbars which are on the right.

# Proposed solution C
Allow every user to pick their favorite spot and sizing through the extension settings

**Comment by tprouvot** [comment]
Solution C implemented
