### ISSUE TITLE
Problem retrieving record type name in random objects

### ISSUE THREAD

**Issue by SFDCdavidesi** [tprouvot/Salesforce-Inspector-reloaded#273]
**Make sure to read the troubleshooting section before creating an issue**

- [ x] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.

**Describe the bug**
When I am viewing a record detail and I click on salesforce inspectgor reloaded, some objects displays the record type name, and some objects don't display it.
I've tried with edge and chrome in several instances : production , full sandbox and developer sandbox, and it displays the record type of custom object in all sandboxes, but does not display the record type name of Custom object (Case) in any of the sandboxes.
I've just realized that one of the objects have 4 different recordtypes.
all recordtypes are active and have the same configuration.
I am logged in as a System Admin with all privileges.

I can see the recordtype name of just 1 of the recordtypes, not being able to see any of the other 3.

**To Reproduce**
1. Go to '...' It is hard to reproduce outside my org. go to any record having record types
2. Click on '....' salesofrce inspector reloaded 
3. Scroll down to '....' see record type
4. See error -> record type is not visible

**Expected behavior**
I am expecting to see record type information
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macos 14.2.1 (23C71)
 - Browser [e.g. chrome, firefox, edge] Chrome Version 120.0.6099.216, edge Version 120.0.2210.121
 - Version [e.g. 1.20]

**Additional context**

**Comment by tprouvot** [comment]
Hi @SFDCdavidesi,
It is a known issue #255 recently fixed and will be available in the[ beta version ](https://chromewebstore.google.com/detail/salesforce-inspector-relo/lopjgjcglnncikiocpacfdbkmpbfmkcf) probably tomorrow (currently in chrome review process).
If you install the beta version the update will be automatic

**Comment by SFDCdavidesi** [comment]
Thank you, a colleague of mine already pointed me to that issue.
Thanks!

**Comment by tprouvot** [comment]
Hi @SFDCdavidesi,
The fix is available in the [beta version](https://chromewebstore.google.com/detail/salesforce-inspector-relo/lopjgjcglnncikiocpacfdbkmpbfmkcf) which has just been released on chrome 🚀
