### ISSUE TITLE
'Show fields API names' not shown first time component open

### ISSUE THREAD

**Issue by oleg-mastriukov** [tprouvot/Salesforce-Inspector-reloaded#288]
**To Reproduce**
1. Go to any record
2. Click on the '<' button to show the Inspector window
3. Pay attention that the 'Show fields API names' is not there
4. Close the Inspector window and open it once again
5. Pay attention that now the button is shown

**Expected behavior**
The button shows up from the first time

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 22H2
 - Browser Chrome 120.0.6099.225
 - Version 1.21

**Comment by tprouvot** [comment]
Hi @oleg-mastriukov,
Could you share more details (screenshot / screen recording) about your page detail (page layout? flexipage ? dynamic form ?)

**Comment by tprouvot** [comment]
@oleg-mastriukov I'm closing the issue for the moment, feel free to add details so that I can investigate it.

**Comment by oleg-mastriukov** [comment]
@tprouvot sorry for the late response.
Please find a video attached. The first object is Opportunity where dynamic forms are enabled, the second is Account where dynamic forms are disabled. For both objects, it reproduces when I first open the record. If then I open another record of the same object, the 'Show fields API names' button is shown. If I refresh a page and open a record again, then again the button is not shown until I open the extension again.

https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/46223141/347784c3-7cf5-4c6e-997e-38d7942a3daa

**Comment by tprouvot** [comment]
Hi @oleg-mastriukov thanks for the video ! 
I'm not able to reproduce the issue.. Is it happening on one particular org or on all of them ? 
@MD931 FYI

**Comment by oleg-mastriukov** [comment]
@tprouvot I checked several orgs, this behavior was in all of them. If I can share any useful details, then let me know how to do that

**Comment by tprouvot** [comment]
@oleg-mastriukov Have you any colleagues experiencing the same issue ? 
Are you using any VPN or proxy ? If yes could you test with a direct connexion ?

**Comment by oleg-mastriukov** [comment]
@tprouvot I think I found the reason: the issue reproduces only if I have the [Grammarly](https://chromewebstore.google.com/detail/grammarly-ai-writing-and/kbfnbcaeplbcioakkpcpgfkobkghlhen) extension running

**Comment by tprouvot** [comment]
@oleg-mastriukov good catch ! 
Is it ok if I close the issue ?

**Comment by oleg-mastriukov** [comment]
Yep, I think there are not many people who face the same issue, so there's no sense in fixing the issue
