### ISSUE TITLE
[popup] Ability to choose header theme

### ISSUE THREAD

**Issue by tprouvot** [tprouvot/Salesforce-Inspector-reloaded#294]
**Is your feature request related to a problem? Please describe.**
It would be great if users can choose between light and dark theme in the popup

**Describe the solution you'd like**
<img width="278" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/c268577e-7958-48c0-a93d-181a2da4909d">
<img width="275" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/f5ee1451-f1b6-4b5d-bca0-00f489eb90dc">

**Additional context**
Based on linkedin poll, the default theme would be dark by default, the preference will be stored in a localStorage variable and available from options page
<img width="525" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/659d4fab-9ef5-417e-b1c1-00170c634727">

**Comment by tprouvot** [comment]
FYI @nshulman

**Comment by nshulman** [comment]
Noted 👍

**Comment by Astisme** [comment]
Developments on #64 will also change the header colors based on the preferred color scheme.

**Comment by tprouvot** [comment]
Delivered in 1.23
