### ISSUE TITLE
Generate Connect App Token Redirect

### ISSUE THREAD

**Issue by sullivannich** [tprouvot/Salesforce-Inspector-reloaded#297]
**Make sure to read the troubleshooting section before creating an issue**

- [x ] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.

**Describe the bug**
When I click the "Generate Connected App Token" button, then click allow, I get redirected to the data export page. If I hit the back button on my browser it tends to mess with the connected app token.

**To Reproduce**
Click generate connected app token (assuming you've already set this up)
Click Allow
Be redirected to Data export page

**Expected behavior**
I would hope to be able to go back to the salesforce page i was on. I typically want to login as a different user, so getting redirected to the data export page isn't ideal.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 121.0.6167.140

**Additional context**

**Comment by tprouvot** [comment]
Hi @sullivannich,

Since we changed the way we generate tokens in the new version, would you mind test on the [beta version](https://chromewebstore.google.com/detail/salesforce-inspector-relo/lopjgjcglnncikiocpacfdbkmpbfmkcf) which is the incoming 1.22 ?

**Comment by sullivannich** [comment]
I'm sorry, my work computer is locked down and I would have to get this approved by our IT security, and it would not get approved. So I can't download the beta version.

**Comment by tprouvot** [comment]
Hi @sullivannich,
Are you able to enable developer mode on chrome ?
If yes you could install the extension locally and test the beta version

**Comment by sullivannich** [comment]
This has also been disabled by my IT Security team.
