### ISSUE TITLE
[data-export] Large amount of suggestion fields is not scrollable

### ISSUE THREAD

**Issue by vranisimo** [tprouvot/Salesforce-Inspector-reloaded#301]
**Describe the bug**
When there is a large amount of object fields, the field suggestions is showing only the topmost fields and the view is not scrollable.

**To Reproduce**
1. Go to data export
2. Start with the normal SOQL select
3. Click on the Show all suggestions button
4. If there is a large amount of object fields, you can only see the top part of the fields section, and can't scroll to the bottom or to the results div/element.

**Expected behavior**
I would expect that all possible object fields are displayed in a scrollable html element. I noticed that all html elements for all fields are available in the DOM, but it is just not possible (without browser dev tools) to scroll or focus to them.

**Screenshots**
Fields are not previewed due to privacy, but there is a red rectangle indicator just to prove that a scrollbar is not present.
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/2634396/f2a7cfa4-19af-4cfa-a3d0-2f27bc377788)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - Version 121.0.6167.140 (the latest version at this moment)

**Comment by tprouvot** [comment]
Will be available in 1.23 and earlier on beta version
