### ISSUE TITLE
"Show All Data" of a object show the wrong data type length / Wrong field type  

### ISSUE THREAD

**Issue by efcdilascio** [tprouvot/Salesforce-Inspector-reloaded#311]
**Make sure to read the troubleshooting section before creating an issue**

- [X ] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.

**Describe the bug**
Using "show all fields" function from a Salesforce object, some fields are shown with the wrong data type length

**To Reproduce**
1. Open "Inspector" in any salesforce page
2. Go to "Objects" tab
3. Search for "OrderItem"
4. Click/select order item
5. Click "Show all data" button
6. Search for "Quantity" in filter field in the top right corner

**Expected behavior**
A list of all object fields is shown

**Screenshots**
![INSPECTOR ERROR 01 Captura de tela 2024-02-20 152329](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/51202926/9c01aa91-bdd2-409b-8967-c7b3d6d40221)

![INSPECTOR ERROR 02 Captura de tela 2024-02-20 152329](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/51202926/2e00e004-3ee4-4689-b2d7-f717b3f4bb25)

**Desktop :**
 - OS: Windows 11 Home Single Language 23H2 | version 22631.3155 | Windows Feature Experience Pack 1000.22684.1000.0
 - Browser: Microsoft Edge
 - Version: 121.0.2277.128 (Compilação oficial) (64 bits)

**Additional context**

**Comment by tprouvot** [comment]
Hi @efcdilascio,
You are correct there is a difference between data shown in Salesforce and the one in inspector.
The data displayed in inspector is the one from the 'EntityParticle'

<img width="1031" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/3cc77319-faa7-4e94-af83-649c70aaa293">

I'll update it to reflect Salesforce view
