### ISSUE TITLE
[popup] Prevent Popup from appearing multiple times

### ISSUE THREAD

**Issue by Astisme** [tprouvot/Salesforce-Inspector-reloaded#320]
**Make sure to read the troubleshooting section before creating an issue**

- [x] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.

**Describe the bug**
On some SF pages, the Button & Popup are shown more than once.

**To Reproduce**
1. Go to "Social Customer Service"setup page (this isn't the only page this happens on)
2. See duplicated button

**Expected behavior**
Have only a single button/popup on each page.

**Screenshots**
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/96465880/5d001207-3d1c-4a85-a94a-10adfee5da07) | ![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/96465880/d35c542a-91da-4a45-9ac7-d5d47e2dced6) | ![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/96465880/e42c75ef-65d2-4f95-8674-c7931013a1af)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, firefox, edge]
 - Version [e.g. 1.20]

**Additional context**
1. Update the manifest.json's "all_frames" key to false (or remove it)
2. Publish
3. Profit

Evidence:
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/96465880/8850214c-b60b-4382-a7f2-9de8a82a4bd7)
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts#all_frames
```
[false](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts#false)
    Inject only into frames matching the URL requirements which are the topmost frame in a tab.
```

**Comment by tprouvot** [comment]
Hi @Astisme,
The second icon and popup can have more information than the first one and I think this is useful.

Best example is for deployment detail :

<img width="1189" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/1612e090-4a61-40bf-b5ed-66f5ff86f0fa">

I don't think this is a big issue and would require too much work to have it merged, what do you think ?

**Comment by Astisme** [comment]
Oh ok, I didn't know about that.
Let's trash this issue then.
