### ISSUE TITLE
Configure default values for Batch Size and Threads in  Data import

### ISSUE THREAD

**Issue by ritterblau** [tprouvot/Salesforce-Inspector-reloaded#329]
Is your feature request related to a problem? Please describe.

When importing, by default they are done at Batch size 200 and Threads 6
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/6390945/4d51e611-9a61-4654-af40-0864603a1a57)

This can be modified from the data-import.js file, but updating the extension resets it. 
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/6390945/26138235-8f43-4c08-b60d-70b579f8b265)

Would it be possible to configure it from the configuration?

**Comment by tprouvot** [comment]
Will be released in 1.23 🚀

**Comment by ritterblau** [comment]
Thanks a lot @tprouvot
