### ISSUE TITLE
Browser Crash Upon Copy Data on Data Export

### ISSUE THREAD

**Issue by danielmotasousa** [tprouvot/Salesforce-Inspector-reloaded#331]
When I try to export records and copy them, the browser crashes. I tried on multiple browsers and multiple Orgs. The threshold for the crash seems to be around 6000+ rows and 4+ columns. (I Tried with 4 columns and 7000 records and crashed)

**To Reproduce**
1. Go to 'Data Export'
2. Query 4 columns (including Id) and make sure there are at least 7000 results
3. Try to copy the records (in any format excel, CSV...)
4. See error crash

**Expected behavior**
The records should simply copy.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Edge, Chrome
 - Edge ( 122.0.2365.66 ), Chrome (122.0.6261.95)

**Comment by tprouvot** [comment]
Hi @danielmotasousa,
I think it depends on many parameters such as the fields length you are exporting, your computer configuration etc.

7k. seems to be significatively less than what I am able to copy (I just tested with 60k and it works like a charm)
Please check if you have the same behaviour on another computer (maybe ask your colleagues to test it ?)

You may have another extension which cause the issue

**Comment by tprouvot** [comment]
Hi @danielmotasousa,

Did you had a chance to check of other computers ?

**Comment by akingumusel** [comment]
Hi @tprouvot,
This breaking change was introduced and implemented very badly in my opinion.
- We have the API Access Control enabled, and was using a connected app and consumer secret to generate access token.
- With the new version, the extension directly **hides the buttons** and shows the Access Token Expired - Generate New Token message (like a toast). So there is no way to enter our own consumer secret, and we do not want to use the generic Connected App that the extension introduced.
- We found a workaround to remove the API version, reload the page where the buttons appear again, populate the consumer secret into the new section in Options, then click on Generate New Access Token button and then enter the API version again.

I believe we should be given to see the standard buttons at all t
<img width="358" alt="Screenshot 2024-03-11 at 13 34 49" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/16411513/ac4ad1af-5883-4776-bbfc-70a3738263b3">
imes.

**Comment by tprouvot** [comment]
Hi @akingumusel 
I think you are commenting the wrong issue but let me try to give you an answer.
The consumer key you previously entered was still saved in your localStorage, you just had to update the callback url to remove the host parameter according to the documentation.

When you said "remove the API version" you mean remove the API Access control ? 

FYI
In the future version we introduced a cog icon in the popup footer in order to access options page even when the token is not valid.
