### ISSUE TITLE
Pressing Cmd+Space to insert all field name autosuggestions is not working for MacBook (iOS)

### ISSUE THREAD

**Issue by aakash-jansari** [tprouvot/Salesforce-Inspector-reloaded#332]
Pressing Cmd+Space to insert all field name autosuggestions is not working for MacBook (iOS).

**To Reproduce**
1. Go to Export Query.
2. Start to write the query. i.e Select Id from Account limit 10
3. press cmd+space after "Id" in above query.
4. all field name suggestions are not auto added to query

**Expected behavior**
This functionality works with windows and ubantu where pressing ctrl + space would auto add the field name suggestions to query, but not working for MacBook

I have tried with multiple combinations
- Cmd+Space
- Option+Space
- Ctrl+Space
All of them are not working.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser : Chrome
 - Version : 122

**Comment by tprouvot** [comment]
Hi @aakash-jansari,
The shortcut is Ctrl+space on mac also.

I think you may have a particular configuration on your device, please check previous discussions on this topic:
https://github.com/tprouvot/Salesforce-Inspector-reloaded/issues/170

Let me know if you succeed to use the shortcut !
