### ISSUE TITLE
Edge Add-on is in version 19, while Chrome is in 22

### ISSUE THREAD

**Issue by hj-dieset** [tprouvot/Salesforce-Inspector-reloaded#343]
I'm using Edge and the extension is in version 1.19, while in Chrome it's in 1.22. Why is this?

**Comment by tprouvot** [comment]
Hi @hj-dieset ,
I did not update the edge extension yet, but recently I found out that chrome extensions can be installed in Edge which means you can  install the chrome 1.22 on Edge

![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/b13778c2-1809-461f-ac8c-25357f7bedc6)

**Comment by hj-dieset** [comment]
Ahh, thanks for your useful tip and quick reply!
