### ISSUE TITLE
Not able to update with external Id field

### ISSUE THREAD

**Issue by Damecek** [tprouvot/Salesforce-Inspector-reloaded#347]
**Describe the bug**
Not able to update records with External Id in the Import Tab due to 
```
Error: The field mapping has no 'Id' column
```
**To Reproduce**
1. go to import data
2. paste data with external id and field to update
3. select update
get error

**Expected behavior**
no error, records should be updatable with external ids
**Screenshots**
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/46635736/31a8200b-bbbc-41d6-97f0-53fdfc90e57e)

**Desktop (please complete the following information):**
 - OS: 14.3.1 (23D60)
 - Browser Chrome Version 122.0.6261.112 (Official Build) (arm64)

**Comment by tprouvot** [comment]
Hi @Damecek,
Please select "Upsert" to be able to use external Id

<img width="485" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/77d05bbb-1e2f-44bc-9d15-106d178401a2">

**Comment by Damecek** [comment]
That seems weird to me, but ok as an workaround.

**Comment by tprouvot** [comment]
This is not a workaround 😄 it is the way the [API](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_calls_upsert_upsertresult.htm) works
