### ISSUE TITLE
[data-export] Add Query Template to Options page

### ISSUE THREAD

**Issue by chanclement8** [tprouvot/Salesforce-Inspector-reloaded#349]
**Is your feature request related to a problem? Please describe.**
There will be times where i will need to create SOQL with the WHERE condition of **field NOT LIKE '%abc%'**. there are times where i dont remember the exact format and have to google for it.

**Describe the solution you'd like**
It would great if we can enhance the **Template** drop down to include a SOQL snippet for WHERE clause with NOT LIKE. Example below
SELECT ID FROM ACCOUNT WHERE (NOT Name like 'ABC%')

**Describe alternatives you've considered**
Quick google to search for the exact syntax

**Additional context**
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/8043138/60c7e09a-2ad3-45e5-b5d2-642af278dd1d)

**Comment by tprouvot** [comment]
Hi @chanclement8 ,
You can add your own templates by following this article

https://tprouvot.github.io/Salesforce-Inspector-reloaded/how-to/?h=templa#add-custom-query-templates

**Comment by tprouvot** [comment]
Since this is not very user friendly I can add this option to the options page

**Comment by tprouvot** [comment]
Should be available in 1.23 and beta earlier !

<img width="895" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/16490965-ec4f-42d7-a534-8f24febe1ee3">
