### ISSUE TITLE
[data-import] Hide unecessary columns in queries with fields from related object

### ISSUE THREAD

**Issue by CamilleGuillory** [tprouvot/Salesforce-Inspector-reloaded#352]
Hide those columns when doing queries with related object
SELECT Id,Account.Name,**_Account.RecordType.DeveloperName_**
<img width="1711" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/45099363/17c94d9a-623c-43a9-b222-00d6bb3fafc0">

**Comment by dufoli** [comment]
@CamilleGuillory I have implement such feature in https://github.com/dufoli/Salesforce-Inspector-Advanced can you check if it is find for you ?

**Comment by CamilleGuillory** [comment]
Hi @dufoli 
Yes it is working!
<img width="753" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/45099363/7443f5a3-4cdb-4597-a18a-e65f275a1665">
