### ISSUE TITLE
RecordType Name suggestion in where clause

### ISSUE THREAD

**Issue by CamilleGuillory** [tprouvot/Salesforce-Inspector-reloaded#353]
**Describe the bug**
The recordtype values are missing when we want to specify them in a SOQL query:
<img width="1450" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/45099363/81c0c98b-55d8-4b22-84aa-1deb1f2d54d7">
It is working fine with Picklist fields

**Comment by tprouvot** [comment]
Humm works for me, we can check this at the office on your computer

![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/f493e020-8873-4475-897f-1278b11273e6)

**Comment by tprouvot** [comment]
For peps on Mac who are trying to use the autocomplete shortcut, if Ctrl+Space is not working try Ctrl+Cmd+Space

**Comment by CamilleGuillory** [comment]
Hi @tprouvot 
FYI the MAC shortcut retrieves ALL record types of the org.
ex: the list is not filtered to display only RT of the Contact object

**Comment by tprouvot** [comment]
You're right this is not normal and will be a good improvement 👍
