### ISSUE TITLE
Regenerate Access Token message on every Salesforce login

### ISSUE THREAD

**Issue by hgolov** [tprouvot/Salesforce-Inspector-reloaded#357]
**Make sure to read the troubleshooting section before creating an issue**

- [x ] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.

**Describe the bug**
Starting today (and a collegue of mine reported yesterday), each time I login to SF I am presented with a message that my Access Token Expired and a link to regenerate

**To Reproduce**
1. Login to Salesforce
2. Click on the translucent arrow to open SIR
3. See error

**Expected behavior**
The regular panel to open.

**Screenshots**
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/1575666/430fede8-c3d6-4b70-b9df-400fa407d359)

**Desktop (please complete the following information):**
 - OS: MacOS, Sonoma
 - Browser: Chrome
 - Version 122.0.6261.129

**Comment by tprouvot** [comment]
Hi @hgolov,
Have you enabled the API Access control on your org ?

**Comment by hgolov** [comment]
I'm not sure what you mean - I've been using this since the org was spun up, I use SFDX with the org, etc. Is there a specific setting in the plugin that I need to enable?

**Comment by tprouvot** [comment]
Have you enabled a restriction to prevent users who are not using a connected app to use APIs ?

<img width="809" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/b2e398dc-1377-437f-825e-a9d68d32d656">

Could you paste a screenshot of the chrome dev console filtered for the extension ?
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/04921fc3-ce06-403e-931b-1605c131358e)

**Comment by hgolov** [comment]
Strange, not finding that setting:
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/1575666/f4c7af40-ce18-4178-ba4a-72bcb5d57637)
Global (Setup) Search:
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/1575666/37dce19a-0094-4e48-92f4-cb5c782a387c)
Here's the js console:
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/1575666/3f8b6b39-234e-4609-84ef-425a2c64f6e7)

**Comment by tprouvot** [comment]
If you don't find the setting it means that you did not enabled it (you must create a support case to see this option).

Were you able to use inspector reloaded in its previous version on this org ? 
What is your profile ? 
Are you able to use other salesforce extension on this org (MavenTool, ORGanizer, legacy inspector) ?

**Comment by hgolov** [comment]
I was able to use this, yes.
I'm System Admin
I can use Maven Tool.

**Comment by tprouvot** [comment]
Could you try to login in the same org from incognito mode and try again ?

**Comment by hgolov** [comment]
I logged in in incognito, but the plugin doesn't show. In general my plugins aren't available in incognito.

**Comment by tprouvot** [comment]
Could you activate it just for the tests ?

**Comment by hgolov** [comment]
You're teaching me a lot today :) I didn't know I could do that. I enabled and it worked properly in incognito.

**Comment by tprouvot** [comment]
Did you clicked on "Generate new token" at least once ? 
My guess is : you had a timeout session, the banner appeared (and should not but will be fixed in future version), you clicked on generate new token and it saved the token in you localStorage.

To valid that, could you inspect popup (right click **on the popup**) and then go to Application tab

<img width="484" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/41afd850-d551-4c95-aa3d-eacf122b2580">
Search for "access_token" and then delete the entries

![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/b4e4e31b-2193-4aaf-b3d1-9e48f8c3bd5e)

**Comment by hgolov** [comment]
Thank you so much! This solved it for both my colleague and myself!

I really appreciate the time you spent helping us, on top of this amazing plugin.
