### ISSUE TITLE
[API Access Control] Installation error with default connected app

### ISSUE THREAD

**Issue by LCh07** [tprouvot/Salesforce-Inspector-reloaded#358]
**Make sure to read the troubleshooting section before creating an issue**

- [ ] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.

**Describe the bug**
When I click Install from the default App Oauth Entry I get the error message attached

**To Reproduce**
1. Go to  SETUP>>
Connected Apps OAuth Usage
2. Click on '.Install' next to entry (blocked) matching the default  'Salesforce Inspector reloaded' App

4. See error attached

**Expected behavior**
App can be installed and then allowed

**Screenshots**
attached

**Desktop (please complete the following information):**
 - Windows 10 Enterprise
 - Browser chrome,
 - Version [e.g. 1.22
<img width="794" alt="Salesforce Inspector Reloaded-Installation Error" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/101558781/636be822-5136-4289-ad0b-4adb9e641fb3">

**Additional context**

**Comment by mehdisfdc** [comment]
Hi @LCh07 , thank you for reporting your issue.

I have 2 questions to help us understand your issue:

1) Do you have [API Access Control](https://help.salesforce.com/s/articleView?id=sf.security_api_access_control_about.htm&language=en_US&type=5) enabled in your org? (I suppose the answer is "yes", otherwvise you wouldn't try to install the connected app?)

2) What is your Salesforce Edition (you can check under Setup | Company Information)?

**Comment by LCh07** [comment]
Hello @mehdisfdc,

Thanks for coming back to me. 
We do have API access Control enabled and our edition is Enterprise Edition.
Its worth noting that the installation worked in a Dev sandboxe but is now failing as I move it up to a devpro and a partial.
Anything else you need me to check just let me know.

Thanks

**Comment by mehdisfdc** [comment]
Thank you @LCh07 .

I'm not sure why you get this error is some of your sandboxes (this is not something I managed to reproduce on my end). If this becomes a blocking issue for you, you may want to log a case to Salesforce Support so that they could investigate why your are getting this error in some of your orgs.

But, out-of-curiosity, why are you trying installing the connected app if you don't use API Access Control?

**Comment by tprouvot** [comment]
Hi @LCh07,
Could you try to create a custom connected app and then I can show you how to save it in localStorage manually (or with the 1.23 beta version) 

The goal is to check if you are facing the issue with a custom connected app also

![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/e761ba59-f777-4abc-b60b-18f0fa8a28b4)

**Comment by LCh07** [comment]
@tprouvot @mehdisfdc ,
Thanks for the updates. See the latest below:

We do have API access Control (answer = yes to your question)
We want to install the default connected app to avoid the issues we faced 2 weeks ago during your last upgrade


Tried via Edge: this also failed
If that's any clue I start this in Lightning and after I get the error my experience switches back to Classic

Now logged this under Case #46584367 with Salesforce Support.

I have created other Default Apps in this org last week without problem. I would rather not go down the route of creating custom for this one since we are trying to go default to avoid issues. Migrating to default will already be an effort and would not want to invest time in a half solution.

Thanks

**Comment by tprouvot** [comment]
@LCh07 Ok I'll try to help the support investigating this issue

**Comment by tprouvot** [comment]
Hi @LCh07,
Have you seen case support message ? 
They're trying to reach you

**Comment by tprouvot** [comment]
I'm posting the resolution in order to help other who are facing the same issue:
https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/#managed-application-installation-error
