### ISSUE TITLE
[flow-builder] Access flow versions from builder

### ISSUE THREAD

**Issue by RebbePod** [tprouvot/Salesforce-Inspector-reloaded#362]
**Is your feature request related to a problem? Please describe.**
When on a flow it's really annoying to get to the screen showing all flow verisons

**Describe the solution you'd like**
a button when in a flow to take me to all versions

I'm assuming this isn't difficult to implement being that the DefinitionId is right on the flow

**Comment by tprouvot** [comment]
<img width="859" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/93b87580-80e1-49f8-9705-61369adff148">

**Comment by RebbePod** [comment]
That was quick, awesome!

**Comment by tprouvot** [comment]
Yes it does open the same page as 'View Details and Versions' link.
It will be available in beta probably within two weeks
