### ISSUE TITLE
Generate New Token Error

### ISSUE THREAD

**Issue by JAMooreAnalytics** [tprouvot/Salesforce-Inspector-reloaded#373]
**Make sure to read the troubleshooting section before creating an issue**

- [Yes] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.

**Describe the bug**
I am receiving a 'Generate New Token' error every time I open inspector in a particular org. I looked at the troubleshooting and found the error, but the suggestion led me to entering code into the console within the inspector. I received the following warning: "Warning: Don’t paste code into the DevTools Console that you don’t understand or haven’t reviewed yourself. This could allow attackers to steal your identity or take control of your computer. Please type ‘allow pasting’ below to allow pasting." I do not have much experience with this, so I would not feel comfortable going forward with this solution.

**To Reproduce**
1. Go to the side error to enter salesforce inspector
2. observe the 'Generate New Token" Error

**Expected behavior**
I would expect Inspector to open easily without generating a new token every time like it previously was.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS (Mac) and Windows
 - Browser: Chrome
 - Version: 122.0.6261.112

**Comment by tprouvot** [comment]
Hi @JAMooreAnalytics ,

Instead of running the code (which is totally sure and only apply to extension local storage) you can manually delete the entries ending with 'access_token'.
To access those entries of local storage please check this how to 

https://tprouvot.github.io/Salesforce-Inspector-reloaded/how-to/?h=migrate#migrate-saved-queries-from-legacy-extension-to-salesforce-inspector-reloaded

**Comment by tprouvot** [comment]
Hi @JAMooreAnalytics 
Since I think the solution provided should solve your issue I'll close it.
Feel free to comment if you still have trouble, I'll re-open it
