### ISSUE TITLE
[popup] Generate token displayed when sessions expired and API access control not configured

### ISSUE THREAD

**Issue by tprouvot** [tprouvot/Salesforce-Inspector-reloaded#375]
**Make sure to read the troubleshooting section before creating an issue**

- [x] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.

**Describe the bug**
Since the version 1.22, we released a new way of generating token for api access control.
Unfortunately this banner appears also when the session is expired and may lead users to click on 'Generate new token' link which makes them use the default connected app and refresh a new token every day.

**To Reproduce**

**Expected behavior**
Generate new token banner appears only if the user decided to use a connected app.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, firefox, edge]
 - Version [e.g. 1.20]

**Additional context**

**Comment by mehdisfdc** [comment]
@tprouvot Yes I think it's the best solution.

When adding the "Generate New Token" banner I did not anticipate the situation where "non-API Access Control" users would try to use the extension on a expired session. I agree that this situation should be addressed, and the solution you propose sounds good to me.
