### ISSUE TITLE
Use the escape (esc) key to exit popup

### ISSUE THREAD

**Issue by ktag3000** [tprouvot/Salesforce-Inspector-reloaded#378]
When the popup is open can you also allow it to be closed by pressing the escape key? It closes for a mouse click on the screen already, which is great.

**Comment by tprouvot** [comment]
Good idea I'll take a look 👍

**Comment by tprouvot** [comment]
@ktag3000 will be released in the 1.24 🚀

**Comment by ktag3000** [comment]
Awesome! Thank you!
