### ISSUE TITLE
[popup] Login As user in an incognito window

### ISSUE THREAD

**Issue by alanjaouen** [tprouvot/Salesforce-Inspector-reloaded#381]
**Is your feature request related to a problem? Please describe.**
When I login as a user, it can be frustration to loose my admin access to monitor in real time user action.

**Describe the solution you'd like**
I would like to use the "login as" button, but the action will take place in a new incognito window

**Describe alternatives you've considered**

**Additional context**

**Comment by tprouvot** [comment]
@alanjaouen Great !
