### ISSUE TITLE
[popup] Add view user summary link

### ISSUE THREAD

**Issue by tprouvot** [tprouvot/Salesforce-Inspector-reloaded#386]
**Is your feature request related to a problem? Please describe.**
With summer24 release, a new summary view is available for users, provide this link on the user tab.

<img width="275" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/6d82d7b3-75c9-4ded-a705-8e6e0ddbe7ff">

**Comment by tprouvot** [comment]
Hi @Asitt100,
Is your sandbox in Summer 24 ?
You can check on the org tab

**Comment by Asitt100** [comment]
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/155186069/70343e12-c05d-4a9e-9057-6c927abcad0c)

**Comment by Asitt100** [comment]
i guess summer update will work then.
thank you!
