### ISSUE TITLE
Support new setup domain 

### ISSUE THREAD

**Issue by akalatksy** [tprouvot/Salesforce-Inspector-reloaded#389]
**Is your feature request related to a problem? Please describe.**
Inspector button/popup does not appear on "Setup" pages in _some newly_ created scratch orgs.
Example URL of "Setup" page: 
`https://customer-connect-6379-dev-ed.scratch.my.salesforce-setup.com/lightning/setup/SetupOneHome/home`

**Describe the solution you'd like**
Add *.salesforce-setup.com to allowlists of the extension.

**Additional context**
The issue is related to the Winter'24 Release Note: 
https://help.salesforce.com/s/articleView?id=release-notes.rn_general_setup_domain_prepare.htm&release=246&type=5
Affected salesforce org in on CS215 instance with Spring '24 Patch 17 version.

**Comment by tprouvot** [comment]
Hi @akalatksy,

Thanks for the info I missed this new domain 👍 
I just created a scratch org and I could experience the new domain.

I have to check but the fact that we now have two different domains for the same org may lead to other issues in reloaded.
I'll keep you informed

**Comment by tprouvot** [comment]
I'll add it to the [beta](https://chromewebstore.google.com/detail/salesforce-inspector-relo/lopjgjcglnncikiocpacfdbkmpbfmkcf) version, should be available in a day or two

**Comment by tprouvot** [comment]
Hi @akalatksy, @greigmaterialize, @bacasystems-IT, @shnrz
The beta version has been published with the new domain support, the scratch org I used to test the dev yesterday does not use the new domain anymore (Spring '24 Patch 17.2 I guess).

Could you confirm that reloaded is enabled on the new domain ?

**Comment by bacasystems-IT** [comment]
I think they rolled it back after I logged 8+ cases of broken things in less than 50 mins

On Apr 18, 2024, at 5:23 AM, Thomas Prouvot ***@***.***> wrote:

﻿
[EXTERNAL]

Hi @akalatksy<https://link.edgepilot.com/s/bb228188/vfnV1iVaukKcE3mG2AZfWQ?u=https://github.com/akalatksy>, @greigmaterialize<https://link.edgepilot.com/s/e08590d1/-srijI4haUeUKHjlGdHUCQ?u=https://github.com/greigmaterialize>, @bacasystems-IT<https://link.edgepilot.com/s/eca36057/ob2FU1eC_ke8z0r8RCBMFg?u=https://github.com/bacasystems-IT>, @shnrz<https://link.edgepilot.com/s/d7e7ce95/ciY3AIQTVkSbCFLcjdX7Rw?u=https://github.com/shnrz>
The beta version has been published with the new domain support, the scratch org I used to test the dev yesterday does not use the new domain anymore (Spring '24 Patch 17.2 I guess).

Could you confirm that reloaded is enabled on the new domain ?
