### ISSUE TITLE
New Setup URL not yet accounted for

### ISSUE THREAD

**Issue by greigmaterialize** [tprouvot/Salesforce-Inspector-reloaded#391]
The new setup URL is live (at least in sandbox) and not yet accounted for in this app which pretty much makes it useless.

.sandbox.my.salesforce-setup.com is the new url for sandboxes. I don't think it's live yet for prod but it is definitely coming.

To reproduce just go to setup in a sandbox instance and the extension will disappear.

**Comment by tprouvot** [comment]
Hi @greigmaterialize,

I'm closing this issue since it's a duplicate of #389.
