### ISSUE TITLE
Edge Addons shows an old version of Salesforce Inspector Reloaded

### ISSUE THREAD

**Issue by Tratius** [tprouvot/Salesforce-Inspector-reloaded#403]
- [x] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.

**Describe the bug**
Tool Accessibility: This is the link to where Salesforce Inspector Reloaded is found for Edge. It is showing version 1.19 instead of the latest 1.22. Is there a reason for that?
(https://microsoftedge.microsoft.com/addons/detail/salesforce-inspector-relo/noclfopoifgfgnflgkakofglfeeambpd)

**To Reproduce**
1. Visit https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home
2. Search For Salesforce Inspector
3. Click on Salesforce Inspector Reloaded
4. Get recent version. 
5. When using the extension, the newest features are missing! :)

**Expected behavior**
The most recent version (1.22 at the time of this issue being created) would be available from the Edge Addons portal. 

**Screenshots**
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/143458002/2bab3701-1668-4f8b-b5e2-2fff7855d7fd)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 124.0.2478.67

**Additional context**
This occurred as the assumption that the chrome extension and Edge Addon portal would match for Salesforce Inspector Reloaded. While I had installed and received updates, my work colleague was not understanding how his version was not updating and showing the new features. 

FYI, the new features are awesome. 

Trat

**Comment by tprouvot** [comment]
Hi @Tratius,

Yes there's a reason for that but I should write it somewhere in the documentation or in edge application store 👍

In fact chrome extensions can be installed in edge, that means if you visit reloaded chrome web store from edge, you will be able to install chrome version on edge.

**Comment by Tratius** [comment]
Thanks Thomas! It is how we got through it for my colleague. I appreciate the follow up!
