### ISSUE TITLE
[data-import] Throwing error: Unexpected Token ' ' when trying to paste excel

### ISSUE THREAD

**Issue by cgauthierCA** [tprouvot/Salesforce-Inspector-reloaded#417]
**Make sure to read the troubleshooting section before creating an issue**

- [ X ] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.

**Describe the bug**
I use Data Import daily to create records from a query that are filtered in Excel beforehand.  Up until today there have been no issues.  Today when I attempted to paste the excel data to the object ('ResourceAbsence' Standard object from FSL) I cannot paste and get the error "Unexpected Token ' ' "

**To Reproduce**
1. Go to 'Data Import'
2. Set object to ResourceAbsence Object
3. Paste Excel Data (Due to Privacy I am not able to provide the excel data - but it is in this general format - see attached)  The file i provided will paste properly, i assume it must be due to some of the punctuation in the gantt label columns?  I have tried removing all single quotes from file, and it still fails
![error ](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/142833495/0f61708e-60bc-40d2-8ee6-30e19fbe4e85)

**Expected behavior**
Excel Data can be pasted with no issue. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version [Version 124.0.6367.119]

**Additional context**

**Comment by cgauthierCA** [comment]
[Excel Sample1.xlsx](https://github.com/tprouvot/Salesforce-Inspector-reloaded/files/15226687/Excel.Sample1.xlsx)
Attached Sample File

**Comment by Fransiscu** [comment]
I had the same problem, in my case it was caused by double quotes in the selected field to udpate. Got rid of them and it started working again (used excel export)

**Comment by tprouvot** [comment]
Hi @cgauthierCA,
I can't reproduce the error, for me pasting does not give me any error with your file..

<img width="1229" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/e8f902ae-f77a-424c-a613-b0806814e331">

Are you facing this issue with all data import ? 
Could you try with google sheet import or CSV ?

**Comment by nexionly** [comment]
I encountered this as well turned out to be double quotes " I did a Search and Replace " > ' .
