### ISSUE TITLE
Version 1.23 - No flag indicating to user a new access token is required

### ISSUE THREAD

**Issue by LCh07** [tprouvot/Salesforce-Inspector-reloaded#420]
**Make sure to read the troubleshooting section before creating an issue**

- [ ] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.

**Describe the bug**
in Version 1.22 the Orange flag makes it clear to users to request a new token. In new 1.23 they have to select it from multiple options which can lead to confusion.
Will 1.23 be forced to users at some point? currently its only for new downloads.

**To Reproduce**
see attached

**Expected behavior**
Clear indication of specific action required

**Screenshots**
see attached
[SF Inspector Reloaded - 1.23 Access Token.docx](https://github.com/tprouvot/Salesforce-Inspector-reloaded/files/15233243/SF.Inspector.Reloaded.-.1.23.Access.Token.docx)

**Desktop (please complete the following information):**
 - Chrome 124.0.6367.119

**Additional context**

**Comment by LCh07** [comment]
[SF Inspector Reloaded - 1.23 Access Token.docx](https://github.com/tprouvot/Salesforce-Inspector-reloaded/files/15233269/SF.Inspector.Reloaded.-.1.23.Access.Token.docx)

**Comment by tprouvot** [comment]
Hi @LCh07,

We introduced a small change in 1.23 in order to display the new token required banner only if a token was generated at least one time from the Generate new token button.

We've done this because some users clicked the generate new token when their sessions was expired which lead them to use the connected app even if they did not wanted to.

Could you try and let me know if you are seeing the expected behaviour ?

**Comment by tprouvot** [comment]
1.23 is released on Chrome and may take some time to be deployed on existing installations.
Have you tried to disable / enable it ?

**Comment by LCh07** [comment]
Hi @tprouvot,

Thanks for clarifications. It looks like new version is getting pushed by Chrome (was the case on my laptop 5 mins ago).
New behaviour looks in line with what we had on 1.22, looks fine. Thanks
<img width="298" alt="1 23-Retest" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/101558781/a9fac99d-d636-40d0-ba36-da3bf81505e9">
