### ISSUE TITLE
Option to remove Object colum in data extraction

### ISSUE THREAD

**Issue by NdeFrutos** [tprouvot/Salesforce-Inspector-reloaded#422]
Hello,

I think it could be a good idea to be able to remove the object column when querying lookup fields. This would be specially usefull when copying in excel format :)

![Captura de pantalla 2024-05-07 123047](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/106304638/c761f6f2-a556-4446-973a-46e42c9790ae)

Thank you very much, love your work!

**Comment by tprouvot** [comment]
Hi @NdeFrutos,

This is already tracked in this one #352 and under review from this [PR](https://github.com/tprouvot/Salesforce-Inspector-reloaded/pull/406).

This should be available soon !
