### ISSUE TITLE
[data-export] Saved query with character ':' are not pasted correctly

### ISSUE THREAD

**Issue by Anassi89** [tprouvot/Salesforce-Inspector-reloaded#428]
When is saved a Query with the Character ':' the query is not pasted correctly; only the values after the ':' are pasted

1. Create a Query
   select count(id) from account where CreatedDate  < LAST_N_DAYS:10
2. Click on 'Save Query'
3. Select the Saved Query
4. See error (It's pasted only the Value '10')

The query should be pasted correctly

![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/5946184/0726c63e-18ed-46a6-882e-0096b6760e23)

Desktop:
 - Win11
 -  Chrome
 - Version 124.0.6367.91

**Comment by tprouvot** [comment]
Hi @Anassi89,
Ok I could reproduce the bug, this is only when no label is set.
I'll fix this 👍

**Comment by tprouvot** [comment]
TODO: 

- add a label property to savedHistory instead of using a separator
- handle data migration to the new model (probably in background.js with onInstalled.addListener on "update" reason)
- track this code to be removed on the next version
