### ISSUE TITLE
[show-all-data] Error on clicking on the dropdown of the sub-fields on the Inspect Page

### ISSUE THREAD

**Issue by IamKewal** [tprouvot/Salesforce-Inspector-reloaded#430]
**Describe the bug**
When the dropdown of any subfield is clicked, then following error is displayed:
Error getting field setup links for(fieldName): Cannot read properties of undefined (reading 'DurableId')

**To Reproduce**
1. Go to 'Show all data' of any account (or any other object with compound address field)
2. Click on 'the dropdown' corresponding to the BillingCity
3. Scroll up to the top
5. See error "Cannot read properties of undefined (reading 'DurableId')"

**Expected behavior**
Error should not be displayed, even if setup page is not available.

**Screenshots**
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/105919065/e38b8ea5-537a-4f13-b20c-d501e221b1db)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 1.23

**Comment by tprouvot** [comment]
Issue fixed, will be available in the next version, thanks @IamKewal
