### ISSUE TITLE
[popup] Show field API Name not working without clicking in detail page

### ISSUE THREAD

**Issue by CamilleGuillory** [tprouvot/Salesforce-Inspector-reloaded#431]
**Describe the bug**
I have to click in the detail record zone in order to display the "show API Name" button.

**Expected behavior**
I want the button to be always available

**Comment by MD931** [comment]
Hi @tprouvot @CamilleGuillory 

@CamilleGuillory I can't reproduce the bug :(
Does this bug occur on all record pages for all objects ? Are you using page layout or dynamic forms ? Does this happen in an environment that is in Summer '24 ?
When you say "click in the detail record zone" do you mean "click on detail tab" ?
Do you have a way to reproduce this bug ?
Thank you.

**Comment by CamilleGuillory** [comment]
Hi @MD931 
I managed to reproduce it.
I thought that I needed to click on the detail page, but in fact I need to wait. I click too fast.
See below:
![2024-05-17_09-16-54 (1)](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/45099363/5abc3d82-1467-486d-be40-e4a208c67795)

First fast click -> button is missing
Then clicks to close & re-open, the button is visible

**Comment by jeffrutter** [comment]
This seems to be broken for us on Accounts and some custom objects. However if we turn the feature on in the case page and navigate to our custom object off of it the api names are showing still

**Comment by tprouvot** [comment]
Hi @jeffrutter,
Could you open a new issue describing the problem with video or gif ?
