### ISSUE TITLE
Rename "master" branch to "main"

### ISSUE THREAD

**Issue by Julian88Tex** [tprouvot/Salesforce-Inspector-reloaded#448]
Why: https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main
How: https://gist.github.com/danieldogeanu/739f88ea5312aaa23180e162e3ae89ab
More context: https://github.com/github/renaming

**Comment by tprouvot** [comment]
Hi @Julian88Tex ,

I was wondering if some people really feel uncomfortable with the master branch naming convention or if it was more a marketing approach from big companies to avoid potential troubles.
 If you created the issues I am assuming that you prefer the "main" convention, but I am asking the question by pure curiosity.

Anyway it's a small change and I can take care of that 👍

**Comment by Julian88Tex** [comment]
@tprouvot Hey, thanks for asking. It's a fair question, in my opinion. I can say personally I feel uncomfortable when I see it since it seems, at the very least, dated at this point. I would liken it to when I hear someone call me a homosexual instead of gay. It is not intentionally offensive but seems unnecessarily triggering if it can be avoided. Whenever I join a new company, and I see repos with `master` to me, it is a signal that they at least aren't discussing these topics, and I would expect to see similar gaps in things like accessibility and diversity.

Here's a little bit more I found on the topic: https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/

**Comment by tprouvot** [comment]
Thanks for exposing your point of view Julian ! I don't feel uncomfortable to change the branch name to main so I'll update it 👍

**Comment by tprouvot** [comment]
Fixed !

**Comment by Julian88Tex** [comment]
@tprouvot awesome!
