### ISSUE TITLE
[general] Custom favicon colour enhancement 

### ISSUE THREAD

**Issue by ext-xixiao** [tprouvot/Salesforce-Inspector-reloaded#450]
This new feature in beta version allows users to define colors for the org favicons. 
The current _red_ (screenshot) and _orange_ colors are similar. In addition, I'd like the _red_ to be deep-dark-red and visually alarming.  
![Screenshot 2024-06-12 at 10 21 07](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/108273167/95f48a10-3a31-4118-a5d4-ef36007774df)

**Describe the solution you'd like**
The best option is to allow end users to determine colors as they want in a color palette. 
Alternatively, it's ok if the _red_ is enhanced.

**Comment by tprouvot** [comment]
Hi @ext-xixiao,
I did some improvements on the releaseCandidate version which is not yet released as beta. Basically you'll be able to choose any html color 
More details on the how to page 
https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/releaseCandidate/docs/how-to.md#customize-extensions-favicon

**Comment by xixiaofinland** [comment]
Looking forward to the color enhancement in beta! Thanks for pointing to the doc ❤！

**Comment by tprouvot** [comment]
Hi @xixiaofinland ,
I submitted the new beta on the chrome web store yesterday, it should be available soon!

**Comment by tprouvot** [comment]
Hi @xixiaofinland the beta version has been released by Chrome, it should be available soon.

**Comment by xixiaofinland** [comment]
Worked like a charm @tprouvot , thank you so much!
I can happily remove the other plugin now!
