### ISSUE TITLE
[data-import] JSON import format in "Data Import" issue

### ISSUE THREAD

**Issue by luca-miglioli** [tprouvot/Salesforce-Inspector-reloaded#452]
Current Version: 1.23
Browser: Chrome Version 126.0.6478.57 (Official Build) (64-bit)

Steps to reproduce the error:
1. Open Salesforce Inspector Reloaded extension
2. Click "Data Import"
3. Configure the Insert as follows
4. API Type = Any
5. Action = Any
6. Object = Any
7. Format = JSON
8. Select the box with the mouse pointer and try to paste inside a well-formatted JSON
9. Notice that nothing happens

Thanks!

Screenshot: ![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/82805521/f874dcd1-0d7f-431e-b1d9-591490e36ba2)

**Comment by tprouvot** [comment]
Hi @luca-miglioli 
This seems to be an issue regarding the format ou your pasted JSON.
To compare with the expected one, please go to data export, run a query and export it as JSON.
Check the differences and replicate in your JSON to be imported.
