### ISSUE TITLE
[popup] BETA: Login As Not Working

### ISSUE THREAD

**Issue by CamilleGuillory** [tprouvot/Salesforce-Inspector-reloaded#457]
**Describe the bug**
I click login as on a user from the pop-up.
I am redirected to:
https://astro--uat.sandbox.my.salesforce.com/servlet/servlet.su?oid=00D92000002Z3bNEAS&suorgadminid=%5Bobject%20Object%5D&retURL=%2Fsetup%2Fown%2Fgroupdetail.jsp&targetURL=%2Fsetup%2Fown%2Fgroupdetail.jsp

<img width="1728" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/45099363/bee024e5-8ed3-4cd0-ab20-ef622338e661">

Error:

```
Unable to Access Page
--
The value of the "suorgadminid" parameter contains a character that is not allowed or the value exceeds the maximum allowed length. Remove the character from the parameter value or reduce the value length and resubmit. If the error still persists, report it to our Customer Support team. Provide the URL of the page you were requesting as well as any other related information.
```

Incognito button is working well

**Comment by tprouvot** [comment]
Hi @CamilleGuillory ,
I also had this behaviour last week with an API only user, is it the case for you ?

**Comment by tprouvot** [comment]
Could you try with main version ? I'm not sure it comes from reloaded but more from an internal change on the loginAs functionality

**Comment by tprouvot** [comment]
I just reproduced the error, you're right its a regression from reloaded 👎

**Comment by CamilleGuillory** [comment]
Yes I tested main version and it is working

**Comment by CamilleGuillory** [comment]
Also if you fixed it, I would love to have the login As Incognito not in the dropdown 
<img width="278" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/45099363/83bf1987-d961-4943-bea2-eada949c75ea">

I would save a click :)

**Comment by tprouvot** [comment]
I will release the fix during the day, it should be available tomorrow on the store (already in releaseCandidate)
