### ISSUE TITLE
Access Token expired - generate new token

### ISSUE THREAD

**Issue by BTJason** [tprouvot/Salesforce-Inspector-reloaded#459]
**Make sure to read the troubleshooting section before creating an issue**

- [ ] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.

**Describe the bug**
When logging in for the first time every day, I am always faced with "generate new token".  I see the article about this issue but dont know how to correct that through the edge dev console.  how can I resolve this?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 1.23 installed chrome version on edge.

**Additional context**

**Comment by tprouvot** [comment]
Hi @BTJason ,
Same resolution on Edge by opening the dev console and executing the code. Other option is to uninstall and reinstall the extension.
Let me know if you could fix the issue

**Comment by tprouvot** [comment]
Hi @BTJason,
Did you managed to solve your issue ?

**Comment by tprouvot** [comment]
Yes you can use this [how-to](https://tprouvot.github.io/Salesforce-Inspector-reloaded/how-to/#migrate-saved-queries-from-legacy-extension-to-salesforce-inspector-reloaded).

Only difference is you can do the export with relaoded instead of legacy version.
An improvement would be to expose in the UI this setting to allow standard copy paste from option page !

**Comment by BTJason** [comment]
Thanks. Should I continue to grab the extension for the chrome store to obtain the latest version or will the edge version also be available with the save version?


Jason Rojas

Salesforce Administrator

[cid:ae7bf296-fcfb-4122-b6b5-981f6681ce45]<https://calendly.com/jason-rojas-1>


 [cid:ecb4993c-5d23-4536-bf8f-c3dd75fedbc1]




T:+1  703-923-8015

8219 Leesburg Pike, Suite 800, Tysons, VA 22182 USA

***@***.*** | bakertilly.com<http://www.bakertilly.com/>


Baker Tilly Advisory Group, LP and Baker Tilly US, LLP, trading as Baker Tilly, operate under an alternative practice structure and are members of the global network of Baker Tilly International Ltd., the members of which are separate and independent legal entities. Baker Tilly US, LLP is a licensed CPA firm that provides assurance services to its clients. Baker Tilly Advisory Group, LP and its subsidiary entities provide tax and consulting services to their clients and are not licensed CPA firms.

________________________________

**Comment by BTJason** [comment]
Thanks. Should I continue to get the latest version for the Chrome Store when using Edge?  or will the Edge extension be at the same version?
________________________________

**Comment by tprouvot** [comment]
You should use the chrome version since it's updated more often than edge one.

**Comment by EEDAG** [comment]
Fixed when I reloaded it. Just Fyi.
