### ISSUE TITLE
[popup] Ability to easily change profile language

### ISSUE THREAD

**Issue by Roland-Circle8** [tprouvot/Salesforce-Inspector-reloaded#463]
**Description:**
I have to change my language quite a lot from Dutch to English to German and back. It is almost impossible to use the Salesforce setup in Dutch or German so this MUST be English :-) 

But I need to look at the user interface a lot in Dutch and German because my users use their native language and it is easier to support them that way. Now I have to go into my profile, change the language and go back to the page I was working on several times a day.

**Possible solution:**
Is it possible to create a switch in the inspector that allows me to change the interface language with a simple click of a button.

**Comment by tprouvot** [comment]
Hi @Roland-Circle8,
I'll take a look to see if it's easy to implement !

**Comment by Roland-Circle8** [comment]
Thanks! I have the beta version running, so if it is possible I will be happy to help you with testing.

**Comment by Mart-User** [comment]
I also need this feature, sometimes working on projects with multiple languages, I often had to switch to validate both perspectives.

**Comment by tprouvot** [comment]
Language switcher is coming guys !

![2024-12-04_15-51-31 (1)](https://github.com/user-attachments/assets/a0fa1e40-ee76-4ee6-b745-b051a3d417e3)
