### ISSUE TITLE
[data-export] Incorrect RecordType Values Displayed for Queried Object

### ISSUE THREAD

**Issue by CamilleGuillory** [tprouvot/Salesforce-Inspector-reloaded#466]
When executing the following SOQL query:

```

SELECT Id, Account.RecordType.DeveloperName 
FROM Contact 
WHERE RecordType.DeveloperName = 'CRM_ClientContact' 
AND Account.RecordType.DeveloperName = '<some_value>'
```
the RecordType.DeveloperName values are incorrectly sourced from the Contact object instead of the Account object as specified in the query.
<img width="1796" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/45099363/4478b52b-57ea-4b3b-b061-ff5d9307d9d5">

Expected Behavior:
The query should return RecordType.DeveloperName values from the Account object.

Actual Behavior:
The query returns RecordType.DeveloperName values from the Contact object.

Steps to Reproduce:

Execute the provided SOQL query in the developer console or any other query tool.
Observe that the RecordType.DeveloperName values are sourced from Contact instead of Account.

**Comment by tprouvot** [comment]
Good catch @CamilleGuillory 👏 
Issue is solved and will be deployed on beta soon
