### ISSUE TITLE
[beta][data-export] Tooling API:  UNEXPECTED EXCEPTION:TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by Wintermute1974** [tprouvot/Salesforce-Inspector-reloaded#474]
**Make sure to read the troubleshooting section before creating an issue**

- [x] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.

**Describe the bug**
The Tooling API does not return any records.  Instead, it returns the error message ```UNEXPECTED EXCEPTION:TypeError: Cannot read properties of undefined (reading 'length')```

**To Reproduce**
1. Open the Data Export screen.
2. Select the Tooling API
3. Enter the following SOQL Query:
```
SELECT Id
FROM ExternalString 
LIMIT 5
```
4. Press the "Run Export" button.

**Expected behavior**
Five Custom Labels should appear in the search results.

**Actual behavior**
This error message is returned:
```UNEXPECTED EXCEPTION:TypeError: Cannot read properties of undefined (reading 'length')```

**Screenshots**
The same query works fine in Workbench:
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/43496898/4fd8d5ab-9b03-4a35-b470-1718528d83a8)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 11 Version 23H2 (Build22631.3737)
 - Browser: Microsoft Edge Dev 128.0.2677.1 (Official build) dev (64-bit) 
 - Version: v1.24.3 / 61

**Additional context**
This worked the last time I needed to use the Tooling API.  That was probably three weeks ago.

**Comment by tprouvot** [comment]
Hi @Wintermute1974,
I am reproducing the error and it seems that comes from the recent updates concerning the SOSL and GraphQL new languages support.
I'll fix it ASAP and update the beta version, should be available in the begining of next week.
Until this moment could you use the main version ?

**Comment by Wintermute1974** [comment]
Hi @tprouvot 
I will use the main version for now.  Thank you for the quick reply.

**Comment by tprouvot** [comment]
@Wintermute1974 thank you for using the beta version and highlighting this bug ! 

![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/101db05d-6543-486f-b10f-cede8f5ec854)

**Comment by tprouvot** [comment]
Fixed on releaseCandidate, will be added to beta soon

https://github.com/tprouvot/Salesforce-Inspector-reloaded/commit/ef48d1199d13dc0bf651926373bb8847b0cedc3a

**Comment by Eiton** [comment]
Same error message is returned when you select "Add deleted records?".

**Comment by tprouvot** [comment]
> Same error message is returned when you select "Add deleted records?". 

Hi @Eiton ,
This issue has been raised in the #538 and I provided a workaround
