### ISSUE TITLE
[data-import] Choose to Keep Account Team with Data Import

### ISSUE THREAD

**Issue by sshapiro-articulate** [tprouvot/Salesforce-Inspector-reloaded#478]
**Is your feature request related to a problem? Please describe.**
When I need to Data Import an ownership change for Accounts, I cannot use this tool because the default in Salesforce is to delete existing Account Team Members.

**Describe the solution you'd like**
There is a setting available from Salesforce to Keep Account Team as part of [OwnerChangeOptions](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_header_ownerchangeoptions.htm) and I would like the ability to toggle that setting as part of Data Import.

**Describe alternatives you've considered**
The only alternative solution I have is to use a different tool such as the Data Loader tool which does have that setting available.

**Additional context**
Here is some additional documentation from Salesforce: https://help.salesforce.com/s/articleView?id=000390190&type=1

**Comment by tprouvot** [comment]
Hi @sshapiro-articulate ,
Just to make sure my understanding is correct, are you updating the owner with data import page or from show all data page ?

**Comment by sshapiro-articulate** [comment]
Hi @tprouvot,

I was changing the owner from the Data Import page.  We periodically need to re-distribute accounts due to territory realignments, promotions, or departures so it requires a mass update for any number of reasons.

Thanks.

**Comment by tprouvot** [comment]
Hi @sshapiro-articulate ,

I'm thinking of adding a new field in the import page which allows users to enter specific headers based on their need.
It will allows you to use any header available in the [SOAP Headers](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/soap_headers.htm).

It's a bit gueeky but I'm assuming those who are looking for enabling those options understands those configurations.
I'm currently working on finding the right configuration for the OwnerChangeOption and will provide examples in the documentation.

<img width="505" alt="image" src="https://github.com/user-attachments/assets/0b19ad3a-bbd7-480b-a98d-c336438dae05">

**Comment by sshapiro-articulate** [comment]
That sounds great! The more flexibility we can have, the more powerful the tool will be.  I really appreciate your quick attention to this!
