### ISSUE TITLE
Prevent use of the extension to non Admin users, or manage permissions

### ISSUE THREAD

**Issue by iquatragithub** [tprouvot/Salesforce-Inspector-reloaded#479]
**Is your feature request related to a problem? Please describe.**
We see many users in our org that are using this extension to manipulate data not in layout avoiding our restrictions.

**Describe the solution you'd like**
We would like a way to manage permissions so that SysAdmin can decide who can use this extension or not.

**Describe alternatives you've considered**
Use permitted only to Sysadmin

**Additional context**
none

**Comment by tprouvot** [comment]
Hi @iquatragithub,
Please take a look at this
https://tprouvot.github.io/Salesforce-Inspector-reloaded/how-to/#use-sf-inspector-with-a-connected-app
