### ISSUE TITLE
Popup Arrow Button Position can be Out-of-View making Extension Unusable

### ISSUE THREAD

**Issue by mckayhowell** [tprouvot/Salesforce-Inspector-reloaded#480]
**Describe the bug**
When the UI "Popup arrow button orientation and position" Position control is set to extreme values, it can be partially or entirely off the screen. If it's entirely off the screen, then it becomes impossible to regain access to the extension without uninstall/reinstall (which deletes all saved data) since it is no longer possible to access the options to restore the position.

**To Reproduce**
1. Go to Options -> User Experience -> "Popup arrow button orientation and position"
2. Set Orientation to Vertical
    a. High End: when Position is 98% or 99% then it is partially off-screen. At 100% it disappears from the screen entirely.
    b. Low End: Position 0% is further from the expected edge of the browser window than 1%
3. Similar behavior is seen when Orientation is Horizontal

**Expected behavior**
The popup button should always be entirely contained within the browser window and should never be partially/fully out of view.

**Screenshots**
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/144164005/92d0fd23-429b-46aa-9dea-70b7bea847be)

**Desktop**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 126.0.6478.127

**Comment by tprouvot** [comment]
Hi @mckayhowell ,
Thanks for submitting this issue!
It has been fixed in the coming version that you can already test by checking the link of the beta version in the readme file.
