### ISSUE TITLE
Chrome Keyboard Shortcuts Not Available

### ISSUE THREAD

**Issue by mckayhowell** [tprouvot/Salesforce-Inspector-reloaded#481]
The documentation describes setting Chrome keyboard shortcuts: [https://tprouvot.github.io/Salesforce-Inspector-reloaded/how-to/#customize-extensions-shortcuts](https://tprouvot.github.io/Salesforce-Inspector-reloaded/how-to/#customize-extensions-shortcuts)

However the Chrome Extensions -> "Keyboard shortcuts" does not have an entry for Salesforce Inspector Reloaded (v1.23 installed)

<img width="720" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/144164005/bd8511c6-7757-482c-9fb9-0da97d691479">

<img width="741" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/144164005/52b557c2-e9d6-44f7-8870-67b89f4d695d">

**Desktop**
 - OS: Windows 11
 - Browser: Chrome 126.0.6478.127

**Comment by tprouvot** [comment]
Hi @mckayhowell ,

You're right the fact that this is described in the how to section without mentioning the release version can be confusing. I'll update the documentation.

This feature is available in the beta version (1.24) that you can already use (link in the readme)
