### ISSUE TITLE
Org Limits should contain ? Icon

### ISSUE THREAD

**Issue by CRMTom92** [tprouvot/Salesforce-Inspector-reloaded#485]
When I press on the Org Limits Menu it would be helpful to have a ? like on the Data Import or Export that displays further User Guidance

**Comment by tprouvot** [comment]
Thanks for this feature request @CRMTom92 , what kind of guidance are you expecting from this page ? Link to Sf documentation about limits for example?

**Comment by CRMTom92** [comment]
Yes some kind of link or reference explaining what the limits mean etc.

**Comment by tprouvot** [comment]
Hi @CRMTom92 ,
Org limits page have been restyled and the button has been added.
Will be released in 1.26

**Comment by tprouvot** [comment]
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/940cbc97-09c8-40e9-bd2e-9e4283052fad">
