### ISSUE TITLE
Network error, offline or timeout

### ISSUE THREAD

**Issue by jessPaj** [tprouvot/Salesforce-Inspector-reloaded#488]
**Make sure to read the troubleshooting section before creating an issue**

- [ x] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.
- [ x] I've read the [release note](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/releaseCandidate/CHANGES.md) and the one I'm about to create is not already fixed.

**Describe the bug**
Before, it was possible to do a query to find out which account number was in the search, even if you didn't find it, it was possible to find out whose account ID it was.
Today when searching, the error appeared:
**To Reproduce**
1. Go to 'SELECT Id,CPFCNPJ__c, name FROM Account WHERE CPFCNPJ__c IN ('22258739000130',
'13297677000185',
'03430856000195',
'39802947000151',
'15424999000173',
'32087397000197')
2. Click on 'Run Export'
3. Scroll down to 'Network error, offline or timeout
![Captura de tela 2024-07-12 181526](https://github.com/user-attachments/assets/ace7c821-e936-46ae-b1a0-2e7866260ce7)
'

**Expected behavior**
Before, it was possible to find CNPJ, as if it were a code, to look for the ID of these CNPJs. Today when performing the search the error appeared: Network error, offline or timeout

**Screenshots**

**Desktop (please complete the following information):**
 
 - Browser [e.g. chrome]
 - Version [126.0.6478.127 ]

**Additional context**
n/a

**Comment by tprouvot** [comment]
This might me because of a recent hyper force migration or if you enabled custom domain. Please delete cookies for this website and check again . 
Try to use reloaded from an anonymous window, if it works the issues comes from cookies

**Comment by tprouvot** [comment]
@jessPaj let me know if the test on anonymous window was successful or not. 
If needed I can reopen the issue

**Comment by jessPaj** [comment]
@tprouvot Hi, my test in anonymous windows don't appear the extension Inspector.
I clean the cache, but my test is nos successfull.

**Comment by tprouvot** [comment]
Go to the extension settings in chrome to enable it in anonymous mode

**Comment by jessPaj** [comment]
@tprouvot Keep going the same error...
<img width="951" alt="Captura de tela 2024-07-18 145326" src="https://github.com/user-attachments/assets/645d70f5-1943-44bb-bfad-b12c6bf10490">

**Comment by tprouvot** [comment]
@jessPaj contact me on LinkedIn, we can have a short meeting to debug it. 
One thing that looks weird is that the inspector reloaded icon is greyed out in the chrome extensions section. Looks like you updated the rights associated to the extension..
Maybe try in a new chrome profile, reinstall the extension on it and do not change any settings
