### ISSUE TITLE
[data-export] DataCloud: Field suggestion for Data Lake objects

### ISSUE THREAD

**Issue by ehsky** [tprouvot/Salesforce-Inspector-reloaded#489]
**Is your feature request related to a problem? Please describe.**
Today DataClouds data lake objects can be queried using SOQL, and thereby also this plugin. 

**Describe the solution you'd like**
A want object field suggestion similar to standard salesforce objects when i work with Data Lake objects. 

**Describe alternatives you've considered**
I need something quick and i do not remember the fields i'm using the Data Explorer
If a need a more complex ANSI SQL i'm using the DBeaver with the data cloud connector driver. I will continue using DBeaver, but for the quick checks i'm using SF inspector.

**Additional context**
![image](https://github.com/user-attachments/assets/155e8d66-8fb0-43f9-a1ba-02f49f313bbf)

**Comment by tprouvot** [comment]
Hi @ehsky,
I need to create a DataCloud org to be able to check what is possible.

**Comment by ehsky** [comment]
Now that we got "query editor" in Data Cloud. I see less need for this feature 
<img width="1029" alt="Screenshot 2024-09-03 at 20 59 35" src="https://github.com/user-attachments/assets/d4a3330d-78c6-439d-9f4c-ea22e796ccd0">

**Comment by tprouvot** [comment]
@ehsky  So can I close this ticket ?
