### ISSUE TITLE
[general] Reloaded inspector just not working at all on mac on chrome

### ISSUE THREAD

**Issue by jyoung120** [tprouvot/Salesforce-Inspector-reloaded#492]
**Make sure to read the troubleshooting section before creating an issue**

- [ x ] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.
- [ x ] I've read the [release note](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/releaseCandidate/CHANGES.md) and the one I'm about to create is not already fixed.

**Describe the bug**
I have the inspector loaded in my extensions and it connects to my salesforce but does not give me any informtaion on my records. 

**To Reproduce**
1. go to any record
2. click the inspector
3. it is blank

**Expected behavior**
i expect the inspector to be popualted with record information when i am on a salesforce record and it is opened

**Screenshots**
here is a video: https://app.screencast.com/wLfrMAmU8DMIK

**Desktop (please complete the following information):**
 - OS: 14.5
 - Browser chrome
 - Version 126.0.6478.127

**Additional context**

**Comment by tprouvot** [comment]
When you click on user tab, does it populates the detail with connected user ?

**Comment by jyoung120** [comment]
@tprouvot no, it does not

**Comment by tprouvot** [comment]
Which Salesforce edition do you have ?

**Comment by tprouvot** [comment]
Is api restrictions enabled on your org ?

**Comment by jyoung120** [comment]
We are on unlimited edition and I don’t think api restrictions are on, we use apis all the time. How do I check this? - Jennifer On Jul 15, 2024, at 2:49 PM, Thomas Prouvot ***@***.***> wrote:﻿
Is api restrictions enabled on your org ?

**Comment by tprouvot** [comment]
@jyoung120 you can check it on this menu:

<img width="889" alt="image" src="https://github.com/user-attachments/assets/c13ab677-0da3-425d-ae80-55fb456c276d">

Are you the only one who can't use Inspector in your company ?

**Comment by jyoung120** [comment]
i am the only one at my company that i know of who uses inspector (salesforce team of 1 over here).'
the old inspector worked without any issues.

**Comment by jyoung120** [comment]
and i cannot open that image you sent

**Comment by jyoung120** [comment]
i even made sure to give myself the API access in a permission set and i still dont have access to that menu feature
i also can't get the inspector to load properly on the page: here is a video: https://app.screencast.com/0b0KUQquVT35X

so it seems like something is just disconnected, but i am not sure what to do because the old inspector just worked, i never had to do anything.

**Comment by tprouvot** [comment]
Have you tried to open the extension in an anonymous window? 
Have you tried to uninstall and reinstall the extension?

**Comment by jyoung120** [comment]
how do you use an extension in an incognito window? none of them are avalible. i have removed the extension and reinstalled it, but i will try that again
