### ISSUE TITLE
[Beta] Login as "InPrivate" on Edge not working after limiting user and pw login

### ISSUE THREAD

**Issue by esanzruzafa** [tprouvot/Salesforce-Inspector-reloaded#493]
**Make sure to read the troubleshooting section before creating an issue**

- [X] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.
- [X] I've read the [release note](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/releaseCandidate/CHANGES.md) and the one I'm about to create is not already fixed.

**Describe the bug**
It is not possible to log in as a user in an Edge browser "InPrivate" window after blocking username and password login in Salesforce.
The new "InPrivate" window is opened but on the login page.

**To Reproduce**
1. In Salesforce Setup:
1.1 Disable the user and password login form on "My Domain"
1.2 Activate the "Disable login with Salesforce credentials" on Single Sign-On Settings
2. Try to log in as another user using an "InPrivate" window

**Expected behavior**
A new "InPrivate" Window is opened logged in as the selected user.

**Screenshots**
![image](https://github.com/user-attachments/assets/9601f8a2-e26d-42d2-a941-876a0ffc7511)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: v1.24.4

**Comment by tprouvot** [comment]
Hi @esanzruzafa,
Thanks for creating the issue.

I'm afraid that we won't be able to solve this issue since it seems to be standard behaviour from Salesforce.
Nevertheless I can add this known limitation to the documentation 👍

**Comment by esanzruzafa** [comment]
> Hi @esanzruzafa, Thanks for creating the issue.
> 
> I'm afraid that we won't be able to solve this issue since it seems to be standard behaviour from Salesforce. Nevertheless I can add this known limitation to the documentation 👍

Hi, I don't know why but it's working again in my Salesforce Instance. Thanks for your help and analysis anyway 🙂
