### ISSUE TITLE
[general] Edge Add-On Version Update Request

### ISSUE THREAD

**Issue by smrobert-eb** [tprouvot/Salesforce-Inspector-reloaded#498]
The currently distributed version of the add-on available in Edge is 1.19. This version does not seem to include the ability to select your API version or have any of the other recent updates. 

Current version is 1.23.

Can we get an updated version released? Is there any assistance needed to support its release?

**Comment by tprouvot** [comment]
Hi @smrobert-eb ,
I'm not updating anymore the edge version since you can install the chrome version on Edge. I should update the description on the edge store to mention it
