### ISSUE TITLE
"Try Login As in Incognito"

### ISSUE THREAD

**Issue by mavtron-andrewrusso** [tprouvot/Salesforce-Inspector-reloaded#513]
**Is your feature request related to a problem? Please describe.**
When login in as another user, the "try login as" is a god-send, i use it almost always, but sometimes for troubleshooting, it is better to open incognito so you can make changes and not lose your current tabs or sessions as an admin and can make changes then test to see if it fixed the issue for the user.

**Describe the solution you'd like**
It would be amazing to have a button next to the Try Login As,  that would open the lgin as in an incognito window with one click. <3 

**Describe alternatives you've considered**
Currently, I open Incognito, log in as myself, go to the user page in my normal SF, copy the URL, open the Incognito window, paste in the URL to the user's record detail, and click the OOTB login as.

**Additional context**

**Comment by tprouvot** [comment]
Hi @mavtron-andrewrusso,

I have the pleasure to inform you that @alanjaouen's contribution fits your request 😄 
Already available in the beta version and documented [here](https://www.salesforceben.com/explore-rest-api-with-salesforce-inspector-reloaded/)
