### ISSUE TITLE
Data Export - Ability to hide the "Object" columns when relationship fields are added to a query.

### ISSUE THREAD

**Issue by djhampson** [tprouvot/Salesforce-Inspector-reloaded#516]
When you add a relationship field to a query the "Object" is added as a column. The object from the FROM statement is also added as the first column. 

To save space and improve the readability of the data it would be useful to be able to hide these. 

I know they can be useful for opening the object in SF, All Data etc so I think this should be an option to hide or show. 

EG SELECT Id, Owner.name FROM Account LIMIT 200 will a column called "Owner"

<img width="450" alt="image" src="https://github.com/user-attachments/assets/42f5e1b3-60c5-4757-a3ee-bb936429bae0">

**Comment by tprouvot** [comment]
Hi @djhampson,
This [feature is already available](https://tprouvot.github.io/Salesforce-Inspector-reloaded/how-to/?h=hide#hide-additional-columns-in-query-results) in the beta version and should be released in the main version by the end of the month

**Comment by djhampson** [comment]
Thank you @tprouvot Appreciate it - love this extension
