### ISSUE TITLE
[general] Extend Colored Favicons to the Experience Cloud Builder

### ISSUE THREAD

**Issue by knuckles4ever** [tprouvot/Salesforce-Inspector-reloaded#518]
I spend a significant amount of time working in Experience Cloud sites, and one of the challenges I've encountered is that colored favicons currently don’t work in that environment.

I recently tried out the beta version of the colored favicon feature and absolutely LOVE it! However, I noticed that it doesn’t yet extend to the builder in Experience Cloud.

Would it be possible to extend the colored favicon feature to the associated Experience Cloud sites? This would greatly enhance the user experience and consistency across the platform.

Thank you for considering this request!

**Comment by tprouvot** [comment]
Extension have been enabled on Experience Builder but the favicon is not updated I have to check why

**Comment by knuckles4ever** [comment]
Thanks for the update!  Hoping to see it soon.

**Comment by tprouvot** [comment]
@knuckles4ever this will be part of the 1.25 and should be available next week in beta

![image](https://github.com/user-attachments/assets/c0d99648-43b0-41a8-923b-a59fac614cfe)


<img width="800" alt="image" src="https://github.com/user-attachments/assets/48f60085-d166-475f-aa26-0c1ee0303369">
