### ISSUE TITLE
[popup] Show API Names for Mac User not appearing

### ISSUE THREAD

**Issue by NS2727** [tprouvot/Salesforce-Inspector-reloaded#520]
When looking at a record in salesforce, I used to be able to select Show API names from inspector but now I do not see that option. I see show all data, not API names

**To Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

**Comment by tprouvot** [comment]
Hi @NS2727,
Could you send a screensharing of the page and the popup opening ?

**Comment by tprouvot** [comment]
Hi @BuzzboldJustin ,
Would you be able to send a video sharing of the page loading and the popup ?

**Comment by BuzzboldJustin** [comment]
@tprouvot https://www.loom.com/share/b4987585fc2c437c93b2d32c4f54251b?sid=043ccf9f-5929-463d-a055-eaeadd6aa960

**Comment by tprouvot** [comment]
@BuzzboldJustin  I can see that you are not on the detail tab, could you try to select it and then open the extension?

**Comment by BuzzboldJustin** [comment]
@tprouvot Thank you for catching my oversite.  This works as expected.  I did notice it only works for custom objects. Is that the correct functionality?

**Comment by tprouvot** [comment]
Hi @BuzzboldJustin 
Nope it should be the same behaviour for standard objects also, could you try to open the popup 3 or 4 sec after the page loading is finished ?

**Comment by smileham** [comment]
I'm experiencing the same issue on Windows 11, on the Contact object.

**Comment by tprouvot** [comment]
@smileham are you on the detail tab of the object ?
