### ISSUE TITLE
[data-export] Add an option to the localStorage/options to set the default time zone to show the date in when exporting date/time fields

### ISSUE THREAD

**Issue by kaustubhdapurkar** [tprouvot/Salesforce-Inspector-reloaded#527]
When exporting data along with a date/time field, the rows show time in UTC by default.

Add an option to use the PCs current time zone to show these datetime field values.

PS. I would like to work on implementing this feature.

**Comment by dmoruzzi** [comment]
@tprouvot (not op) while that looks promising, it only supports date functions. Being able to have the time converted to the desired timezone on the data exporter page would be very useful for when I am in an incident call and screensharing. I could adjust the time to reflect the user's local time to make the times more meaningful for the group.

**Comment by tprouvot** [comment]
![image](https://github.com/user-attachments/assets/deca4f43-9e57-4bac-a14f-7cef8c1f9566)

**Comment by tprouvot** [comment]
Will be added to 1.26 and on the beta soon
