### ISSUE TITLE
[popup] the "O" (Object) shortcut is not working when opening the extension window

### ISSUE THREAD

**Issue by DannyGelf** [tprouvot/Salesforce-Inspector-reloaded#528]
**Describe the bug**

If I open the window using ALT + I, all tabs shortcut works, but if I type O nothing happens (and it doesn't take me to the input box to automatically start typing. I have to click it first with the mouse)

Here's a loom I made - https://www.loom.com/share/f912536d0858447a85f068edfaeede9a

**To Reproduce**
1. Open the window (I used the keyboard shortcut - ALT + I)
2. Click "O" to go to "Object"
3. Start typing - see that it DOES NOT type in the text input box (it might trigger other keyboard shortcuts)

**Expected behavior**
Once I stroke "O" in my keyboard, I expect it to select the text input box so I could type the object I'm looking for.

**Screenshots**
Loom video - https://www.loom.com/share/f912536d0858447a85f068edfaeede9a

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: v1.24.5

**Comment by tprouvot** [comment]
Hi @DannyGelf 
So if my understanding is correct, you would like the autofocus goes to the input field of the object tab when opening object tab is that correct ?

**Comment by tprouvot** [comment]
If you hit the tab key, focus will go to the input field

**Comment by DannyGelf** [comment]
@tprouvot Yes, you're right... I might have missed it before (or did you add it recently?)

Still, if you go to another tab (Users, for example), the autofocus goes to the input field, but if you go to Object it does not. Try to go to a different tab, go out of the input box  (click on any other place), and click O. It will change the tab, but the autofocus will not take you to the input tab, you still need to click Tab...

This is not a big deal now that I know tab works haha but I'm bringing it up anyway since it does require knowing this "workaround"

**Comment by tprouvot** [comment]
Hi @DannyGelf ,
No this is in place from the OG version.
In fact the behaviour is different for Object tab since when you are focusing on the input field, it loads the recent records.

**Comment by DannyGelf** [comment]
Got it! So I'll close

**Comment by DannyGelf** [comment]
Expected behavior - use tab when opening the window to autofocus
