### ISSUE TITLE
[general] Salesforce Inspector reloaded stop working on Chrome

### ISSUE THREAD

**Issue by varcrysis** [tprouvot/Salesforce-Inspector-reloaded#535]
Hello, 

 the extension has stopped working in Chrome and I removed and reinstalled it but it is not showing in Chrome anymore maybe because of the inactive service worker

It does show in installed extensions but not in salesforce

I have already tried steps from this page: https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/ but nothing works 

![Screenshot 2024-08-26 at 10 11 56](https://github.com/user-attachments/assets/00fa7f6f-0b9f-46ac-b8c4-f903e66d8e5c)
![Screenshot 2024-08-26 at 10 19 47](https://github.com/user-attachments/assets/240caf86-b3a7-4890-8208-f554576bd526)

**Comment by varcrysis** [comment]
HI @tprouvot my chrome version is already up to date Version 128.0.6613.85 (Official Build) (arm64)
but rolling back to the previous version 1.23 for salesforce inspector reloaded works for me, thank you

**Comment by varcrysis** [comment]
Hi. @tprouvot Also, the Beta version is working fine for me as well

**Comment by tprouvot** [comment]
New version has been released today, I'm closing this issue
