### ISSUE TITLE
[data-export] Not able to query Tooling API? records more than 2000 Records

### ISSUE THREAD

**Issue by avinash-bhuyan-vst-au4** [tprouvot/Salesforce-Inspector-reloaded#543]
**Make sure to read the troubleshooting section before creating an issue**

- [x] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.
- [x] I've read the [release note](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/releaseCandidate/CHANGES.md) and the one I'm about to create is not already fixed.

**Describe the bug**
I am trying to query 'ExternalString' the actual records in org is more than 8000. However, I am not able to query more than 2000 records. Only 2000 records are being retrieved. 

**To Reproduce**
1. Go to 'Data Export'
2. Query 'SELECT Id from ExternalString '

**Expected behavior**
Exact records should be retrieved what is in the org.  Only 2000 got retrieved

**Screenshots**
![image](https://github.com/user-attachments/assets/12a5d5a2-4c59-4e38-befa-eda4e2dbca6d)

![image](https://github.com/user-attachments/assets/3d7e72f3-426e-4235-b552-1aec84611571)

Actual :
![image](https://github.com/user-attachments/assets/41a67fc3-7d2b-4beb-bc1f-4a0cac0ba548)

Expected : 
![image](https://github.com/user-attachments/assets/d84bf3f4-2fa4-479e-9fb8-0352d22628cf)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, firefox, edge]
 - Version [e.g. 1.20]

**Additional context**

**Comment by avinash-bhuyan-vst-au4** [comment]
![image](https://github.com/user-attachments/assets/3d7e72f3-426e-4235-b552-1aec84611571)

![image](https://github.com/user-attachments/assets/41a67fc3-7d2b-4beb-bc1f-4a0cac0ba548)

**Comment by tprouvot** [comment]
That's correct and I could reproduce this behaviour, thanks for raising this issue 🙏 
Let me check if I can find why

**Comment by tprouvot** [comment]
I Fixed the issue, I should deploy the fix by the end of the week

**Comment by avinash-bhuyan-vst-au4** [comment]
Yes, Previous versions were all okay. Thanks for the Update! :)

**Comment by tprouvot** [comment]
Fixed, release sent to google chrome. Should be deployed tomorrow
