### ISSUE TITLE
[data-export] Saved Queries not working as expected

### ISSUE THREAD

**Issue by AyoubLAMEGHAIZI** [tprouvot/Salesforce-Inspector-reloaded#545]
**Describe the bug**
When i try to use a Saved query on the data export, i got on the input area " MyQuery_Name : MyQuery" instead of "MyQuery".

**To Reproduce**
1. Go to 'DATA EXPORT'
2. Click on 'Saved Queries'
3. Select a query (for example: "AccountName : Select Name from Account") on the picklist.
4. See on the input area that you got "AccountName : Select Name from Account" instead of "Select Name from Account" 

**Expected behavior**
I expect to get only the query and not to have the query name.

**Screenshots**
![Screenshot 2024-08-28 at 13 09 30](https://github.com/user-attachments/assets/2c13ec0c-2ffc-4c32-b74d-ab913f6161b4)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Version [1.240]

**Comment by tprouvot** [comment]
Hi @AyoubLAMEGHAIZI,

Could you send me the value of your saved queries to be able to reproduce the bug ? 
You can check how to do so in the step 2 of [this section](https://tprouvot.github.io/Salesforce-Inspector-reloaded/how-to/#migrate-saved-queries-from-legacy-extension-to-salesforce-inspector-reloaded)

<img width="917" alt="image" src="https://github.com/user-attachments/assets/7f71b56a-43f2-45b5-ba7d-0c5e8ea35e8d">

**Comment by AyoubLAMEGHAIZI** [comment]
Hi @tprouvot , here is it:
 {
    "query": "Null First Name:select id from account where FirstName = null",
    "useToolingApi": false
  },

**Comment by AyoubLAMEGHAIZI** [comment]
another value:

  {
    "query": "Account today creation:select name from Account where createddate=today",
    "useToolingApi": false
  },

**Comment by tprouvot** [comment]
Ok @tprouvot  I found out why I wasn't reproducing the error and fixed the issue, will be released by the end of the week !

**Comment by AyoubLAMEGHAIZI** [comment]
Many thanks @tprouvot !

**Comment by tprouvot** [comment]
Thanks for your help and for raising the issue ! 🚀

**Comment by tprouvot** [comment]
Fixed, release sent to google chrome. Should be deployed tomorrow
