### ISSUE TITLE
[data-export] When querying all fields of an object with 'Hide Object Columns : Unchecked'  UI behavior is not expected and not readable

### ISSUE THREAD

**Issue by avinash-bhuyan-vst-au4** [tprouvot/Salesforce-Inspector-reloaded#546]
**Make sure to read the troubleshooting section before creating an issue**

- [x] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.
- [x] I've read the [release note](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/releaseCandidate/CHANGES.md) and the one I'm about to create is not already fixed.

**Describe the bug**
Whenever I am trying to query all fields of any object, and Hide Object Columns is unchecked. the columns are getting expanded after every batch run and data is not readable at all. 

**To Reproduce**
1. Go to 'Data Export'
2. Query SELECT  Ctrl + Space (ALL FIELDS) FROM Object (Preferably where number of records is huge)
3. Make sure Hide Object Columns is unchecked
4. See the data getting retrieved

**Expected behavior**
Columns should not expand

**Screenshots**
![image](https://github.com/user-attachments/assets/894ec7b9-1234-45d5-b245-2e6de8a07082)

It keep on getting expanded after each batch run (as you can see below only one column is visible now): 

![image](https://github.com/user-attachments/assets/ad717eec-9d6a-4c82-8931-f8857f3cee97)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [1.24]

**Additional context**
UI Behavior is not expected

**Comment by avinash-bhuyan-vst-au4** [comment]
Were you able to reproduce it? @tprouvot?

**Comment by tprouvot** [comment]
Hi @avinash-bhuyan-vst-au4 
I haven't checked yet, I'll let you know

**Comment by avinash-bhuyan-vst-au4** [comment]
Yes @tprouvot please, when we are trying to query with bulk fields or all fields of object. I am facing this issue.

**Comment by tprouvot** [comment]
Waiting for the resolution you can locally download the previous release (1.23) from the repo. Let me know if you want some help on this

**Comment by avinash-bhuyan-vst-au4** [comment]
Yes please, can you help me with the steps I know I have to add(Local unpacked) addon file in chrome extension but how to add for 1.23 version?

**Comment by d3nnyP** [comment]
I'm having a similar issue only when querying custom relationships e.g AccountEmail__r.Id.

**Comment by rokga** [comment]
I also have this problem then even after reinstalling, the same problem occurs

**Comment by tprouvot** [comment]
> Yes please, can you help me with the steps I know I have to add(Local unpacked) addon file in chrome extension but how to add for 1.23 version?

You can download previous version from the release page: https://github.com/tprouvot/Salesforce-Inspector-reloaded/releases

1.23 link is https://github.com/tprouvot/Salesforce-Inspector-reloaded/archive/refs/tags/1.23.zip

**Comment by jesicabiecherdh** [comment]
I'm experiencing the same issue. Works fine if window is full size on 2560 x 1440 screen resolution but if the data export window is smaller than the entire screen or resolution is smaller than 2048 x 1152 then the columns just keep expanding.

**Comment by tprouvot** [comment]
Thanks @jesicabiecherdh  for this precision

**Comment by tprouvot** [comment]
Fixed, release sent to google chrome. Should be deployed tomorrow
