### ISSUE TITLE
[data-export] When querying certain fields of an object with 'Hide Object Columns' unchecked, scrolling down or to the right causes the columns to expand excessively, making it difficult to review the data

### ISSUE THREAD

**Issue by rmoussa89** [tprouvot/Salesforce-Inspector-reloaded#549]
**Make sure to read the troubleshooting section before creating an issue**

- [x] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.
- [x] I've read the [release note](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/releaseCandidate/CHANGES.md) and the one I'm about to create is not already fixed.

**Describe the bug**
Querying some fields of an object and scrolling down or to the right causes the columns to expand excessively, making the data unreadable.

**To Reproduce**
1. Go to 'Data Export.'
2. Write the query to extract some fields from the Account object with the necessary filters. Click on 'Run Export.' My query returned 1389 records.
3. Scroll down or to the right in the browser.
4. Observe the column expansion.

**Expected behavior**
Columns width should remains equals the with of the data.

**Screenshots**
Step 2 : 
![IMG-20240901-WA0092](https://github.com/user-attachments/assets/0da4b6d0-539f-40cc-86c6-ac8ad8d641b1)
Step 3:
![IMG-20240901-WA0093](https://github.com/user-attachments/assets/d0a9fc81-2c0a-4349-87f7-341cdcbde5a0)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [e.g. 1.24]

**Comment by tprouvot** [comment]
@rmoussa89 
It looks like this is the same issue as the one I fixed Friday, could you test if the issue still occurs ?

**Comment by rmoussa89** [comment]
Hello, yes the issue is not occuring anymore. thanks!
