### ISSUE TITLE
[general] Colorized favicons for flow debug

### ISSUE THREAD

**Issue by bacasystems-IT** [tprouvot/Salesforce-Inspector-reloaded#552]
- [x] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.
- [x] I've read the [release note](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/releaseCandidate/CHANGES.md) and the one I'm about to create is not already fixed.

**Describe the bug**
When a sandbox org has a colorized favicon that icon does NOT carry over to the flow debug screen which would help a lot when i end up with a bunch of debug tabs to know which org they are from. 

**To Reproduce**
1. Go to extension and set the org to any color for favicon
2. Go to org setup and observe the favicon is the color set
3. Go to a screen flow in setup.
4. Run flow in debug
5. observe favicon color is blue

**Expected behavior**
Color for screen flow favicon debug screen would match for the org
**Screenshots**
All tabs in this pic are the same org 
![image](https://github.com/user-attachments/assets/f29aead5-609a-41bc-b83c-46f499623493)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser [chrome
 - Version v1.25 beta

**Additional context**

**Comment by tprouvot** [comment]
Hi @bacasystems-IT ,
I did not tested yet but yes those pages are built in a different way than the other, like the Experience cloud builder for example.

I'll check if I can do something for those ones, thanks for raising the point !

**Comment by tprouvot** [comment]
WIP ! 
![image](https://github.com/user-attachments/assets/0d62fc63-904a-494a-9cba-88a0956237fb)
