### ISSUE TITLE
[popup] Security Summery buttons

### ISSUE THREAD

**Issue by TachyonicSpace** [tprouvot/Salesforce-Inspector-reloaded#553]
**Describe the solution you'd like**
now that salesforce has a button for viewing security permissions for the users (viewsummary), it would be nice to search a user and have a button to select to open that menu

**Describe alternatives you've considered**
an optional addition could be to do the same for objects since in the fall 25 release, they added a simular setting to objects (leaving here since they are related, can make an additional ticket if needed

**Additional context**
user url ending is: /lightning/setup/ManageUsers/{ID_Here}/summary
object url ending is: /lightning/setup/ObjectManager/{object_Id}/ObjectAccess/view

**Comment by tprouvot** [comment]
Hi @TachyonicSpace 
This is already available by clicking the user's name

<img width="278" alt="image" src="https://github.com/user-attachments/assets/1312d14b-c9c3-453c-8f96-40a4dcf5721c">
