### ISSUE TITLE
[Show all data] REST Error While GET inside Inspect.js and Inspector.js files

### ISSUE THREAD

**Issue by XN-W** [tprouvot/Salesforce-Inspector-reloaded#561]
**Make sure to read the troubleshooting section before creating an issue**

- [x] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.
- [x] I've read the [release note](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/releaseCandidate/CHANGES.md) and the one I'm about to create is not already fixed.

**Describe the bug**
When open any Salesforce Object by clicking "Show All Data", this error displays on the screen. Error::>> "Error describing layout: UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 1618518721-1611420 (-1264710718)". By reading all details in chrome developer tool under Network tab, I found that it is a REST ERROR which is not able to complete GET due to the error inside file Inspect.js...**code line 72** and for Inspector.js.....**code line 91**

**To Reproduce**
1. Go to 'any object inside Salesforce'
2. Click on 'Inspector Icon'
3. then Click on 'Show All Data'
4. On top of the page
5. See error

**Expected behavior**
Displays Error::>> "Error describing layout: UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 1618518721-1611420 (-1264710718)"

**Screenshots**
![wq](https://github.com/user-attachments/assets/6c779825-8087-4cab-90f5-cfabf01b7dde)
![wq1](https://github.com/user-attachments/assets/d31fae69-bb18-4a2f-9cd1-845d3361c8a6)

**Desktop (please complete the following information):**
 - OS: [Windows 11 Enterprise]
 - Browser [Chrome]
 - Version [128.0.6613.120 (Official Build) (64-bit)]

**Additional context**

**Comment by tprouvot** [comment]
Hi,
Are you the one who created a case with Salesforce support?
If so, I think that you mentioned you are also facing the issue with OG version correct?

Does this issue occur in all your environments or only for a particular one? Do you have others colleagues with the same issue or you're the only one ?
Thanks

**Comment by tprouvot** [comment]
Could you give me the current release of your org and the patch (info available under Org tab from inspector's popup)

**Comment by XN-W** [comment]
Hi,

Yes, you are right. It occurs only in the Production environment not on Sandboxes and for everyone in the team.

Current Version: Summer '24 Patch 19.5 / 250.19.5

Thanks,

**Comment by tprouvot** [comment]
Did you enable API Access Control recently or migrate to Hyperforce ?
Can you try to use the extension in anonymous window ?

If it does not work, could you try to use another salesforce extension such as MavenTool or ORGanizer to check if you have the same issue ?

**Comment by tprouvot** [comment]
@XN-W you don't have to install reloaded in incognito mode but only allow access in incognito in chrome extension options for reloaded. 
https://support.google.com/chrome/a/answer/13130396?hl=en

**Comment by XN-W** [comment]
ok thanks for letting me know. But still this issue occurs in incognito mode as well.

**Comment by tprouvot** [comment]
@XN-W I can see that the error seems to be from the describe layout request, could you try to runu the following GET requests in REST Explore page ? 

`/services/data/v61.0/sobjects/InsurancePolicyCoverage/describe/layouts/` and then the one followed by the recordytpe id from your screenshot 
`/services/data/v61.0/sobjects/InsurancePolicyCoverage/describe/layouts/012`

Can you remove the url of your org from the response and paste the result ?

<img width="1427" alt="image" src="https://github.com/user-attachments/assets/6f89f4f8-a141-480e-839e-1b229fd98e8b">

**Comment by XN-W** [comment]
@tprouvot I tried GET requests in Workbench REST Explore page. Following are the responses:

1. For: /services/data/v61.0/sobjects/InsurancePolicyCoverage/describe/layouts
![tyu1](https://github.com/user-attachments/assets/e577d47e-d3e3-42e3-ad5e-6cd173651a81)

2. For: /services/data/v61.0/sobjects/InsurancePolicyCoverage/describe/layouts/012000000000000AAA
![tyu2](https://github.com/user-attachments/assets/ab604572-f439-4d5f-b547-74733bfa0133)

And tried SOQL to find DeveloperName, found nothing.
![tyu3](https://github.com/user-attachments/assets/7bab42cd-0489-463e-890a-85e87c23db3c)

Also used RecordTypeId = '012000000000000AAA' to find but no records found.
![tyu4](https://github.com/user-attachments/assets/aae4ebc6-a711-4108-94dc-b4c0d8796c8c)

**Comment by XN-W** [comment]
@tprouvot Getting same GET responses using SF Inspector Reloaded

**Comment by tprouvot** [comment]
And you told me that you had the same behavior with another object such as Account?

**Comment by tprouvot** [comment]
I think you can update the support case by mentioning that the issue is not related to Inspector but to Salesforce APIs responses. I'll also provide the info internally to the owner of your case.

**Comment by XN-W** [comment]
> I think you can update the support case by mentioning that the issue is not related to Inspector but to Salesforce APIs responses. I'll also provide the info internally to the owner of your case.

Yes definitely, I informed them it is related to APIs. They are like it is not related to Salesforce. Ok will get in touch with them again. Thanks!

**Comment by tprouvot** [comment]
Hi @XN-W,
I've been contacted by the support and the fact they can't access the org makes the debug difficult.
I don't know what are the reasons behind, but would you be open to grant the access during a short period of time (half a day ?) 
If not, could you create a new dev sandbox from prod just to check if the issue still occurs in the new env ? And maybe grant access to support on this less critical environment ?

**Comment by XN-W** [comment]
Hi @tprouvot,

Yes, we cannot provide prod access due to the privacy policy but I am asking them since day 1 about any alternative if they can suggest like you mentioned to create new DEV sandbox or give them DEV access. No body asked me till date. Do not know, what's going wrong with them? It seems they are not taking it seriously or busy with other cases. Now I asked them by myself regarding DEV sandbox.

And I created new DEV org for them where I found the same issue with all objects. Lets see if it helps them.

**Comment by tprouvot** [comment]
Hi @XN-W,

Sorry to hear that you are not satisfied with Salesforce support, I may have found out the issue and hope this will give you satisfaction. 
The support should get back to you soon, on my side I'm trying to reproduce what caused the issue and check if I can fix it.

**Comment by tprouvot** [comment]
Hi @XN-W,
I've seen that the first issue was solved but you are facing a new one ? Could you give more details here ?

**Comment by XN-W** [comment]
Hi @tprouvot 
 
yes, first issue have resolved. There is another starts occurring.

Reproduce steps and behavior are same. 

here you go:

![nw](https://github.com/user-attachments/assets/9232e9ef-f609-44e2-bc6b-13b266c9e9b9)

**Comment by tprouvot** [comment]
@XN-W you are facing this issue as admin?

**Comment by XN-W** [comment]
@tprouvot Its for admin and other one as well (IP.... Sales User). Do not want to expose here.
