### ISSUE TITLE
[data-export] 'Remove Saved Query' Function Not Working

### ISSUE THREAD

**Issue by gaetanik99** [tprouvot/Salesforce-Inspector-reloaded#564]
I encountered an issue with the "Remove Saved Query" feature in Salesforce Inspector Reloaded. The feature is supposed to delete previously saved queries, but it doesn't seem to work. After selecting a query and attempting to remove it, nothing happens, and the query remains in the saved list.

**Steps to Reproduce:**

Open Salesforce Inspector Reloaded.
Go to the "Saved Queries" section.
Select a previously saved query.
Click on the "Remove Saved Query" button.

**Expected Result**: The selected query should be removed from the list of saved queries.

**Actual Result**: The query remains in the list, and nothing happens.

Please let me know if any further information is needed.

Thank you!

**Comment by tprouvot** [comment]
Hi @gaetanik99 ,
You are supposed to have a popup to confirm the deletion, haven't you blocked popups ?

**Comment by gaetanik99** [comment]
Hello @tprouvot,

Thank you for your response. The popup does appear as expected, but when I confirm the deletion, nothing happens. The query is not removed, and it remains in the saved list.

Let me know if there's any additional information or steps you would like me to try.

Thank you!

**Comment by tprouvot** [comment]
Yes can I have a screenshot of the query before selection and after selection ? 
Also could you share the query and name by text ?
Thanks

**Comment by tprouvot** [comment]
I'm closing this issue since the requested information have not been provided, I'll be able to re-open it if needed
