### ISSUE TITLE
Favicon setting not updating SF tab, only Inspector

### ISSUE THREAD

**Issue by clemfernandez** [tprouvot/Salesforce-Inspector-reloaded#565]
**Describe the bug**
The favicon setting does update the SF Inspector tab favicon but not the actual SF org favicon.

**To Reproduce**
Set favicon to whatever color in SF Inspector settings.

**Expected behavior**
Org tab favicon should be updated, not only the Inspector tab.

**Screenshots**
![image](https://github.com/user-attachments/assets/03bb34ab-94fe-45b2-83a2-8be2bde0d8b5)

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2
 - Firefox 130.0
 - SF Inspector 1.23

**Comment by tprouvot** [comment]
Hi @clemfernandez,

This is normal behavior since the favicon for Salesforce pages has been implemented in 1.24

I have to update the firefox version to 1.24 but hadn't the time yet

**Comment by tprouvot** [comment]
I'll comment this issue when the update will be made

**Comment by tprouvot** [comment]
New version available in firefox store !

**Comment by clemfernandez** [comment]
Thank you very much, working as expected now :-)

![image](https://github.com/user-attachments/assets/a12c4436-a766-49a8-baf6-f1dc17a48cbc)
