### ISSUE TITLE
[popup] In the User Search, if the search is done without accents, include results with accents (à, ê, etc)

### ISSUE THREAD

**Issue by bonzi-123** [tprouvot/Salesforce-Inspector-reloaded#566]
**Is your feature request related to a problem? Please describe.**

Because accents are mandatory in order to find a User correctly, quite often I can't find users if I don't include the right accents (à, ê, ö, etc.)

**Describe the solution you'd like**
If someone is searching without accents, bring back the results of any names with the same letters (even if they have accents). For example, if I search for "Veronique" without accents, the users with name "Véronique" should appear.

**Comment by tprouvot** [comment]
Hi @bonzi-123  I understand the requirement but did not found any way to do it technically without reducing the query performances.

**Comment by bonzi-123** [comment]
Hi @tprouvot ok understood, thanks for looking into it! :)
