### ISSUE TITLE
Export to Excel results in csv export (V1.24 & v1.25 BETA)

### ISSUE THREAD

**Issue by hmannick** [tprouvot/Salesforce-Inspector-reloaded#581]
**Make sure to read the troubleshooting section before creating an issue**

- [X] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.
- [X] I've read the [release note](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/releaseCandidate/CHANGES.md) and the one I'm about to create is not already fixed.

**Describe the bug**
In Salesforce Inspector reloaded Version 1.24 (and BETA V 1.25) The Export Copy to Excel function produces .csv values no matter the query or dataset size, Standard or Custom object. 

**To Reproduce**
1. Go to In Browser pop-up from any Salesforce page.
2. Click on Data Export.
3. Scroll down to Export Query, key in a query and Run Export. (i.e. 'SELECT Id, Name, CreatedDate FROM Account WHERE Name LIKE '%[keyword]%' ORDER BY CreatedDate DESC LIMIT 1')
4. Scroll Down to Export Results and select the Copy (Excel) button.
5. Open a new Excel workbook and paste the clipboard data. 
6. Results are (anonymized the exported id): 
"_"	"Id"	"Name"	"CreatedDate"
"[Account]"	"[18digitid]"	"Stark Industries [TEST ACCOUNT]"	"2023-04-25T18:18:35.000+0000"

**Expected behavior**
Select the Copy (Excel) button and when you paste the clipboard data into A1, the data populates each cell formatted exactly as the Export Results display.

**Screenshots**
![image](https://github.com/user-attachments/assets/80bad28e-a08c-46f7-96f8-cdf64f98b97f)
![image](https://github.com/user-attachments/assets/edf3cc11-db4f-42e9-834a-41999b16dd63)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser Chrome
 - Version 129.0.6668.59 (Official Build) (64-bit)

**Additional context**
Issue presented 9/20/2024 ~2PM EST

**Comment by tprouvot** [comment]
I think that your local configuration does not uses the tabs as separator.
If you test the import on Google sheet it should be fine.

**Comment by hmannick** [comment]
Thank you so much @tprouvot! will test to see where this may have changed.
