### ISSUE TITLE
[popup] Expecting Finding Salesforce Object (CRMA Dataset) by ID - None Found

### ISSUE THREAD

**Issue by nickytorstensson** [tprouvot/Salesforce-Inspector-reloaded#584]
**Make sure to read the troubleshooting section before creating an issue**

- [x] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.
- [x] I've read the [release note](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/releaseCandidate/CHANGES.md) and the one I'm about to create is not already fixed.

**Describe the bug**
I am provided with a Salesforce ID of a CRMA Dataset. However, neither the Dataset ID nor the object Dataset can be found with the inspector

**To Reproduce**
1. Open Inspector in org
2. Type in an in-org Dataset record id
3. Type in "Dataset
4. Expected results, actually got none.

**Expected behavior**
Expected Dataset record to be returned - none found
Expected Dataset object definition to be possible to view - none found

**Screenshots**
![{30FD71A6-873A-4FDF-98C4-2873477B096F}](https://github.com/user-attachments/assets/08cf920d-93c8-43bb-a566-36955d0bc382)
![{A601178C-27B8-4E56-9F14-970EF8B9A473}](https://github.com/user-attachments/assets/1d078baf-8a37-401e-b68e-0c859c4b33a2)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 128.0.6613.139

**Additional context**
Perhaps the CRMA object "Dataset" is not yet supported by the inspector. If so, this would be a feature request, I guess.

**Comment by tprouvot** [comment]
Hi @nickytorstensson,
Based on the id prefix you pasted, I can see that the object you are trying to see it EdgeMart and is already available.

<img width="278" alt="image" src="https://github.com/user-attachments/assets/f53eb95f-8894-44f2-a716-1fa286980bbc">
Is this record available when querying it from data export ?

**Comment by tprouvot** [comment]
Do you have the required permissions to see this object ?

**Comment by nickytorstensson** [comment]
Hi @tprouvot,
In my org, I have the standard CRM Analytics Plus Admin permission set assigned to my user. I would presume I have access to view the object from this.

Per your screenshot, I cannot say, why you get these responses in the Extension, and I don't.
