### ISSUE TITLE
[data-export] hint button icons not working on Firefox

### ISSUE THREAD

**Issue by dollarSignUsername** [tprouvot/Salesforce-Inspector-reloaded#586]
**Make sure to read the troubleshooting section before creating an issue**

- [X] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.
- [X] I've read the [release note](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/releaseCandidate/CHANGES.md) and the one I'm about to create is not already fixed.

**Describe the bug**
button icons such as anchor.svg or string.svg don't show up

**To Reproduce**
1. Go to data export
2. start typing field names
3. hints show up with space for icons but not the icons themselves

**Expected behavior**
Icons should be showing up, just like on chrome and edge

**Screenshots**
![image](https://github.com/user-attachments/assets/d397dba7-89f2-43dd-b289-7b522fa813a9)

**Desktop (please complete the following information):**
 - OS: [Win 10]
 - Browser [firefox 130.0.1 (64-bit)]
 - Version [e.g. 1.23]

**Additional context**
I think it's because it's trying to load the icons from chrome-extension url instead of moz-extension

**Comment by tprouvot** [comment]
Hi @dollarSignUsername,
I can reproduce the issue you are facing.
Do you know if it worked before and can be due to a firefox update ?

**Comment by dollarSignUsername** [comment]
I've been using reloaded for about a month and never had working icons. I think it's unlikely it's because of ff, it's probably that url. Extension ID is correct, just the chrome bit needs changing

**Comment by tprouvot** [comment]
Chrome specific url have been removed, will be delivered in 1.25
![image](https://github.com/user-attachments/assets/d0934002-5d18-46d8-8b95-c694d6242f57)
