### ISSUE TITLE
[data-export] Typo in Help Text of Hide Object Columns 

### ISSUE THREAD

**Issue by nmcelheny03** [tprouvot/Salesforce-Inspector-reloaded#587]
**Make sure to read the troubleshooting section before creating an issue**

- [X ] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.
- [ X] I've read the [release note](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/releaseCandidate/CHANGES.md) and the one I'm about to create is not already fixed.

**Describe the bug**
--The help text on the Hide Object columns function within data export reflects "With this option, additionnal columns corresponding to object..."
--There is an extra "n" within the word additional.

**To Reproduce**
1. Go to 'data-export'
2. Hover over 'Hide Object Columns'
3. Typo displays

**Comment by tprouvot** [comment]
Thanks for raising this 👍 
Issue is fixed and will be integrated in 1.25 and beta sooner
