### ISSUE TITLE
[popup] Search for Apex Classes in Shortcuts

### ISSUE THREAD

**Issue by mpekacki** [tprouvot/Salesforce-Inspector-reloaded#591]
It would be very useful to be able to search for Apex Classes in Shortcuts. Sometimes there is a need to check how a particular class looks in a particular environment (for example, production). The standard Setup menu for classes does not allow for search, only filtering by first letter, and it is hard to use, especially in orgs with a large number of classes. Developer Console is a bit better as it allows searching, but it is not always available due to user permissions, especially in production.

Apex Classes in Shortcuts search results would solve this issue. Class name, namespace prefix (if available) and API version could be displayed. Clicking on the class would redirect to Setup page displaying it (`/lightning/setup/ApexClasses/page?address=%2F{ApexClassId}`). If there is a concern that the user will be overwhelmed with too many search results, then an option in configuration (default off) could be added.

I've already added the appropriate code to ` async getMatches(shortcutSearch)` in `popup.js` and tested it locally, so if it's OK I can submit a PR.

**Comment by tprouvot** [comment]
Hi @mpekacki,
Why not ! 

The only concern I have is the performance for the search.
I already had in mind to add an option to let users decide which metadata they want to search for.
ie only on profiles but not on flow, or apex classes and custom permissions ..

**Comment by mpekacki** [comment]
Hi @tprouvot,
I tested it in an org with a fairly large number of classes and I did not notice any performance degradation. I also ran queries like `SELECT Id, Name FROM ApexClass WHERE Name LIKE '%a%' LIMIT 30` manually and they also perform almost instantly. But having it configurable would be ideal, I can even try to include it in my PR, it that's OK. Would it mean getting rid of `metadataShortcutSearch` option and replacing it with `metadataFlowsShortcutSearch`,  `metadataProfilesShortcutSearch`, `metadataPermSetsShortcutSearch` and `metadataApexClassesShortcutSearch`?

**Comment by tprouvot** [comment]
I think I can add the ApexClass search by letting users configuring what metadata they are searching for in the Shortcut:

<img width="1431" alt="image" src="https://github.com/user-attachments/assets/ccc6bf4c-3783-41e3-99ed-ad94550f6ac6">

<img width="278" alt="image" src="https://github.com/user-attachments/assets/b5aa458c-f8a0-4408-83e4-b960578d1a33">
