### ISSUE TITLE
[data-import] Importing large text

### ISSUE THREAD

**Issue by leaojensen** [tprouvot/Salesforce-Inspector-reloaded#592]
When importing large text fields, only about 215 chars are imported. How do I import all the text from Excel into my Rich Text field?

Best regards,
Thomas...

**Comment by tprouvot** [comment]
I don't reproduce this behaviour with textarea or richtext , the test i've made contains 750 characters. 

<img width="1443" alt="image" src="https://github.com/user-attachments/assets/0e1c4326-baae-4562-b6df-9f681fb760cb">

Can you provide more info such as the text (it may contains some special characters)  and screenshots ?

**Comment by leaojensen** [comment]
Hi 
Thank you for the quick answer. You where right. The text included "<<" which the import didn't like. This is fully inderstandable for a RichText / HTML field :-)

Thank you again, really appreciate this!

Thomas...

![image](https://github.com/user-attachments/assets/783cb8bf-0e74-4e61-be8a-0d7c3a61dd5e)
