### ISSUE TITLE
[popup] Load selected record when using list view Split View mode

### ISSUE THREAD

**Issue by mckayhowell** [tprouvot/Salesforce-Inspector-reloaded#597]
It's understandable that the popout Objects tab shows "No record to display" when on a list view's Table or Kanban mode. However, it would be useful if the extension could detect the selected record when the list view is set to Split View mode since the individual record page is loaded in the browser and takes up ~ 2/3rds of the screen.
![image](https://github.com/user-attachments/assets/76c8bbe2-8cc2-42ab-acf5-8b2698947bb9)

**Comment by tprouvot** [comment]
Hi @mckayhowell,
Unfortunately the extension relies on the url to detect the recordID context, I think for the split screen the url does not reflect the selected record and we would not be able to detect the Id.
