### ISSUE TITLE
[data-export] Allow to rename Saved Queries

### ISSUE THREAD

**Issue by bonzi-123** [tprouvot/Salesforce-Inspector-reloaded#602]
**Is your feature request related to a problem? Please describe.**
At the moment, if I want to rename a Saved Query, I have to Save it as a New Query with the updated name and then delete the old query.

**Describe the solution you'd like**
I would like to be able to rename a Saved Query without having to create a new one every time and then deleting the one with the old title.

**Comment by tprouvot** [comment]
Hi @bonzi-123,

The saved queries, history and templates will follow a complete refactoring. 
I'll try to include this requirement in the rework 👍

**Comment by tprouvot** [comment]
Duplicate with #602 (label and query will be saved)

**Comment by bonzi-123** [comment]
Hi @tprouvot #602 is actually this same issue. Were you actually referring to another issue?

Thanks

**Comment by tprouvot** [comment]
Yes sorry I was mentioning the #601
