### ISSUE TITLE
[popup] Keyboard shortcut for "show field names" vs "field creator"

### ISSUE THREAD

**Issue by ktag3000** [tprouvot/Salesforce-Inspector-reloaded#608]
**Make sure to read the troubleshooting section before creating an issue**

- [x] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.
- [x] I've read the [release note](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/releaseCandidate/CHANGES.md) and the one I'm about to create is not already fixed.

**Describe the bug**
The keyboard shortcut for "show field API names" is f. The keyboard shortcut for "field creater" is F. 
When you press f the field creator opens and not show API names. Turning on caps lock does not open field creator. I know on other shorctus that having caps lock on does not let them work (as expected).

**To Reproduce**
1. Open popup and type f
2. Field creator opens
3. Go back to popup and type F
4. Field creator opens 

**Expected behavior**
I was expected f to open "show API names" and F to open "field creator"

**Screenshots**
![image](https://github.com/user-attachments/assets/aac7e4a9-ab9d-43fd-ab9f-19895be41fb9)

**Desktop (please complete the following information):**
- OS: Windows 11
- Browser Edge
-Version 128.0.2739.79 (Official build) (64-bit)
- Inspector version: beta 1.25

**Additional context**

**Comment by tprouvot** [comment]
Thanks for raising the issue! I'll fix it soon !

**Comment by tprouvot** [comment]
Fixed, will be released in beta soon
