### ISSUE TITLE
[field-creator] Missing permissions error

### ISSUE THREAD

**Issue by tprouvot** [tprouvot/Salesforce-Inspector-reloaded#613]
**Make sure to read the troubleshooting section before creating an issue**

- [x] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.
- [x] I've read the [release note](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/releaseCandidate/CHANGES.md) and the one I'm about to create is not already fixed.

**Describe the bug**
Error message: Some fields permissions are missing but we set the permissions.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Field Creator
2. Select an object
3. Enter field api name
4. Add a second field and enter field api name
5. Click on 'Permission button'
6. Choose whatever permission
7. Click Apply to all
8. See 'Some fields permissions are missing' error

**Expected behaviour**
No error since we set the permissions.

**Screenshots**
<img width="1395" alt="image" src="https://github.com/user-attachments/assets/9a2a1ceb-2fd0-4061-9fc1-dcd924eb8e48">

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: 1.25 beta

**Comment by tprouvot** [comment]
@SantiParris8 FYI

**Comment by SantiParris8** [comment]
@tprouvot Noted, fill get it fixed

**Comment by SantiParris8** [comment]
@tprouvot Fixed in #614
