### ISSUE TITLE
[popup] Sign Out as User - Full Logout

### ISSUE THREAD

**Issue by CMilnerHCSS** [tprouvot/Salesforce-Inspector-reloaded#617]
**Description:**
After using Salesforce Inspector Reloaded (SIR) to log in as another user, when I log out as that user from the lightning banner, I am fully logged out of Salesforce even as myself. The security setting "Force relogin after Login-As-User" is not enabled and the same behavior does not occur if I navigate to a user record and log in as that user with the standard Salesforce functionality. The problem only exists when using SIR. Additionally, I did not have this issue on the original Salesforce Inspector extension.

**Steps to Reproduce**
1. Open SIR side panel.
2. Click the 'Users" tab.
3. Search for any internal user and click 'LoginAs'.
4. Click 'Log Out as...' from the top banner.
5. Refresh the page or attempt any navigation and a full logout occurs.

**Expected Behavior:**
I should be logged out as the secondary user, but my main administrator user should remain logged in.

**Screenshots:**
N/A

**Desktop (please complete the following information):**
 - OS: Mac Sequoia 15.0.1
 - Browser: Chrome
 - Version: 129.0.6668.101

**Additional Context:**
N/A

**Comment by tprouvot** [comment]
Hi @CMilnerHCSS 
I can't reproduce this behaviour, for me it follows the option 'Force relogin after Login-As-User'

Are you experiencing this is other orgs ?
You mention that you did not have this issue with OG version but have you retested it ?

![2024-10-15_11-52-29 (1)](https://github.com/user-attachments/assets/789c9375-2f8a-416a-ada3-a65e7cc7ec48)

**Comment by CMilnerHCSS** [comment]
I can no longer replicate this after a browser restart, so I am going to chalk it up to something funky going on in the browser itself. Apologies for the false alarm. I tried just about everything except a browser restart before submitting this. Thanks for the quick response and for looking into this; please feel free to close this out!
