### ISSUE TITLE
[data-export] Double "Show all data" button

### ISSUE THREAD

**Issue by tprouvot** [tprouvot/Salesforce-Inspector-reloaded#63]
**Describe the bug**
When running a query on ContentDocument, we have two buttons "Show all data", one for ContentDocument and the other for ContentNote (the extra one to remove)

<img width="533" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/1ffaeb6a-7a17-4886-8c0d-2a3203c56f19">

`SELECT Id, title FROM ContentDocument WHERE 
LatestPublishedVersionId ='068XXXXXXXX'`

**Comment by baslu93** [comment]
Hi @tprouvot,

I was not able to replicate it.
I'm using the latest version, was it fixed already?

![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/12510531/30a1a125-3994-4037-976a-53b32cb6cce4)

**Comment by tprouvot** [comment]
Hi @baslu93 ,
This is not fixed yet but it may depends on the ContentDocument type or it's context creation. 
I'll check today if I can add more information on the use case

**Comment by tprouvot** [comment]
Hi @baslu93,

It looks like this bug only occurs on orgs that have Notes enabled:

<img width="621" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/f220b07a-e12f-4869-9485-a417bf7fd4d0">

**Comment by baslu93** [comment]
Hi @tprouvot,

Thank you!
I was able to replicate it.

You can assign the issue to me.

**Comment by tprouvot** [comment]
Hi @baslu93,
Sorry for the delay reviewing the PR.

I like the idea to do a callout on ui-api to get the object name but I would prever to do it only when needed.
In our case it would be when objectTypes lenght is more than 1.

There is also a new feature (Query record) which relies on the sobject name and must be available from data-export page.
I think something like this could do the job but we have to manage the delay to get the rest response on time:
``` javascript
    popLink(
      () => {
        let recordId = cell;
        let {globalDescribe} = rt.describeInfo.describeGlobal(rt.isTooling);
        let objectTypes = [];
        if (globalDescribe) {
          let keyPrefix = recordId.substring(0, 3);
          objectTypes = globalDescribe.sobjects.filter(sobject => sobject.keyPrefix == keyPrefix).map(sobject => sobject.name);
          //particular use case when multiple sobjects have the same keyPrefix
          if (objectTypes.length > 1){
            sfConn.rest(`/services/data/v${apiVersion}/ui-api/records/${recordId}?layoutTypes=Compact`).then(res => {
              objectTypes = objectTypes.filter(objectType => objectType == res.apiName);
            });
          }
        }
        return {objectTypes, recordId};
      },
      cell
    );
```
