### ISSUE TITLE
[popup] Add shortcut names preview

### ISSUE THREAD

**Issue by Tal-Fr** [tprouvot/Salesforce-Inspector-reloaded#639]
Hi

It would be great if we can see the full names of search results - specifically on the shortcut tab.

for example - we have many flows that have very similar names with only differences at the end, and today I cannot see which one is which.
would be great maybe if during hovering over the name we could see the full item name

or if there is a way to change the text size so I would be able to see it all

you can see an example here that the last word in the label is after save \ before save , but I cannot see it ( only a small pick from the API name)
![Screenshot 2024-11-04 131441](https://github.com/user-attachments/assets/ba4fcbac-5ae8-4bbb-8b49-f60e99eb3e5f)

Thanks!

**Comment by tprouvot** [comment]
Hi @Tal-Fr,
Sure ! I added the api name as title to be displayed on hover.
It will be part of 1.26 and released on beta probably next month
<img width="348" alt="image" src="https://github.com/user-attachments/assets/612c1257-2493-4f3e-8ee5-bfb98372c5a7">
