### ISSUE TITLE
Export - 1 Tab for fields

### ISSUE THREAD

**Issue by emunoz-at-wiris** [tprouvot/Salesforce-Inspector-reloaded#66]
I like it, but I prefer the original one because when I do an export I am used to select the field from the below list using the tab key. In the original extension is 1 tab, with this one I have to do 4 tabs (Run export -> Account Field Info -> Bulb Icon -> Fields List)

Hope you can fix this, or at least, be able to configure it in "Settings" or something similar.

**Comment by tprouvot** [comment]
Hi @emunoz-at-wiris  !
You're the second person who gave me this feedback this week, so I think other users may have the same feeling.
I'll check if we can do something with the tabindex.

**Comment by emunoz-at-wiris** [comment]
Thanks so mo @tprouvot. The think is that we can do a Run of the query pressing Ctrl + Enter, so for me is better if tab goes directly to fields, as the original extension.

**Comment by tprouvot** [comment]
Will be available in the next version v1.17.
Can be tested locally on [releaseCandidate branch](https://github.com/tprouvot/Salesforce-Inspector-reloaded/tree/releaseCandidate)

**Comment by emunoz-at-wiris** [comment]
thanks very much @tprouvot! I will wait for release version 1.17
