### ISSUE TITLE
[data-export]: "Add deleted records?" label change to "Deleted/Archived Records?"

### ISSUE THREAD

**Issue by mckayhowell** [tprouvot/Salesforce-Inspector-reloaded#662]
Data Export has an option labeled "Add deleted records?". 
Request: change this label to indicate that option covers archived records as well as deleted records
Reason: several admins were falling back to SF Dataloader because they didn't know SF Inspector could export the archived records they needed

**Current**
![image](https://github.com/user-attachments/assets/00f35a80-f9fb-4c05-a255-369d79fa833d)

**Proposed**
![image](https://github.com/user-attachments/assets/f74acf25-e261-499a-8169-da7a3c15a39a)

**Comment by tprouvot** [comment]
Hi @mckayhowell you are right this is not clear at the moment. 
I updated the label 👍 
https://github.com/tprouvot/Salesforce-Inspector-reloaded/commit/2db5e8314517e476bb1c585f1baaac2da2875a13
