### ISSUE TITLE
[show-all-data] Make the class fieldCalculated more visible by increasing the font-weight

### ISSUE THREAD

**Issue by lrlip** [tprouvot/Salesforce-Inspector-reloaded#680]
**Is your feature request related to a problem? Please describe.**
The current `fieldCalculated` class does not clearly differentiate between calculated fields and native Salesforce object fields. This lack of visual or structural distinction makes it difficult to identify which fields are dependent and which are part of the original Salesforce schema, leading to confusion and inefficiencies during use.

**Describe the solution you'd like**
Introduce enhancements to the `fieldCalculated` class to improve clarity:

1. Apply bold text or a distinct color to make calculated fields stand out visually.
2. Add an extra column to explicitly indicate whether a field is a formula or a lookup.

**Describe alternatives you've considered**
1. Alternatively, append a suffix, such as [F], to fields that are formulas, providing immediate recognition of their type.

**Additional context**
-

**Comment by tprouvot** [comment]
Today the difference is represented by `*` char concatenated to the field type

**Comment by lrlip** [comment]
Yes indeed. In Salesforce, a `*` indicates a required field, while in the extension, it marks a calculated field, and required fields are written out explicitly. Aligning these conventions provides a better user experience.
