### ISSUE TITLE
Loading icon or greyed save button when saving a record in show all data screen

### ISSUE THREAD

**Issue by CamilleGuillory** [tprouvot/Salesforce-Inspector-reloaded#69]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Loading icon or greyed save button when saving a record in show all data screen

**Describe alternatives you've considered**

**Additional context**

**Comment by tprouvot** [comment]
Hi @CamilleGuillory ,

How about that ?

![2023-05-05_15-38-27 (1)](https://user-images.githubusercontent.com/35368290/236473360-34aa7d01-31cb-40ee-bfe2-e6df1aeab24b.gif)

**Comment by CamilleGuillory** [comment]
Hi @tprouvot 
Yes that's good
Even better if the blue button can become grey / disable once you click on it :)

**Comment by tprouvot** [comment]
> Hi @tprouvot Yes that's good Even better if the blue button can become grey / disable once you click on it :)

![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/76fd5005-2db6-4895-a55b-9d64a91c8184)

**Comment by CamilleGuillory** [comment]
Oh @tprouvot, thank you. The greyed icon and the disabled button are perfect. I couldn't have asked for more... Or could I? 😈
