### ISSUE TITLE
Save button at the top of the screen

### ISSUE THREAD

**Issue by CamilleGuillory** [tprouvot/Salesforce-Inspector-reloaded#70]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
<img width="1709" alt="image" src="https://user-images.githubusercontent.com/45099363/233450528-505f8ede-c249-4ea5-95f9-d525e3cb1387.png">

**Describe alternatives you've considered**

**Additional context**

**Comment by tprouvot** [comment]
Hi @CamilleGuillory thanks for your feedback.
Since the position of this button is the same as Salesforce'one for saving record I prefer to keep it as is.
