### ISSUE TITLE
Remove Saved Query typo

### ISSUE THREAD

**Issue by kigrup** [tprouvot/Salesforce-Inspector-reloaded#71]
**Describe the bug**
In the Data Export feature, there's a typo on the saved query removal button.

**To Reproduce**
1. Go to 'Data Export'
2. Click on the arrow next to "Save Query"
3. See the typo

**Expected behavior**
The label should say "**Remove** Saved Query" instead of "**Removed** Saved Query"

**Screenshots**
![image](https://user-images.githubusercontent.com/41707166/233626488-1116f414-ee23-4002-bcd3-76aca1dd5a0c.png)

**Desktop:**
 - Browser chrome
 - Version 1.16

**Additional context**
I could fix it and create the PR.

**Comment by tprouvot** [comment]
1.17 is live 🚀
