### ISSUE TITLE
Importing (Use Tooling API?) action is auto set to Update

### ISSUE THREAD

**Issue by Juul1** [tprouvot/Salesforce-Inspector-reloaded#73]
**Describe the bug**
In my case I'm trying to delete flows. When I've set all the parameters (Use tooling API?, object, action, batch size etc). and I've entered the excel copy the action changes automatically from "delete" to "update". 

And the same happens when you copy the options and add that text to the excel copy.

**To Reproduce**
See above

**Expected behavior**
I've expected that the action stays on delete.

**Screenshots**

https://share.cleanshot.com/bP3QNlDJ

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOs
 - Browser [e.g. chrome, safari] Brave browser 
 - Version [e.g. 22] Version 146.140 Chromium: 108.0.5359.99 (Official Build) (x86_64)

**Additional context**

**Comment by tprouvot** [comment]
Hi @Juul1,

Thanks for creating this bug, I can see what's going wrong and it will be fixed in the next release v1.17.

Once fixed, I'll post a comment on the issue.

**Comment by tprouvot** [comment]
Hi @Juul1 ,
This has been fixed and is available on releaseCandidate branch if you want to test it locally, otherwise it will bea available in release 1.17
.

**Comment by Juul1** [comment]
Thanks @tprouvot for the quick fix, sorry missed your message due to holiday. When will you release version 1.17?

**Comment by Juul1** [comment]
Great. thanks for all the effort!
