### ISSUE TITLE
An option to always open a new tab

### ISSUE THREAD

**Issue by hvilminko** [tprouvot/Salesforce-Inspector-reloaded#78]
When opening the Inspector panel and clicking Data Export (for example), I *never* want to open it on top of the existing browser tab. Yes, I can click the middle mouse button to open a new tab instead but it would be great to have an option to always open the Inspector pages in a new browser tab.

**Comment by tprouvot** [comment]
Hi @hvilminko ,

I'm thinking about adding a configuration page to allow users to update some default configuration but it is a heavy development which may comes in a while.
What I can suggest to you is a parameter in localConfiguration that you could update from chrome dev tool.
What do you think about it ?

<img width="947" alt="image" src="https://user-images.githubusercontent.com/35368290/234298526-f12cdd1b-0d8d-4754-afdc-1d49a08e3657.png">

**Comment by hvilminko** [comment]
I understand that a configuration page will require quite a bit of effort to implement. A parameter stored in LocalStorage would do the trick just fine at this point.

**Comment by tprouvot** [comment]
This feature will be delivered in 1.17.

Quick recap, to be able to configure the extension to open links in a new tab you need to :

- Open chrome dev console
- Go to "Application" tab
- Select the local storage from the extension (chrome-extension://fcmoglpkegmpmenokkgkbkjbdhdgneab ...)
- Right click and add "openLinksInNewTab" key and "true" as value
- Refresh the page

![image](https://user-images.githubusercontent.com/35368290/236467803-66d1426d-aa59-42aa-9596-18ccd269f9d3.png)

**Comment by tprouvot** [comment]
1.17 is live 🚀

**Comment by hvilminko** [comment]
Thank you @tprouvot! I added the option and it works great!

**Comment by tprouvot** [comment]
New configuration available
<img width="904" alt="image" src="https://github.com/user-attachments/assets/c2586ae8-49e9-4e3f-8a3f-31b2a3689ea1">
