### ISSUE TITLE
Use Tab to select auto complete options when writing a query in data export. The original inspector addon has this feature.

### ISSUE THREAD

**Issue by asknet** [tprouvot/Salesforce-Inspector-reloaded#83]
**Is your feature request related to a problem? Please describe.**
Use Tab to select suggested options when writing a query in data export. The original inspector addon has this feature. Using mouse to select the autocomplete option increases friction in writing queries.

**Describe the solution you'd like**
Use Tab to select suggested options when writing a query in data export.

**Comment by tprouvot** [comment]
Hi @asknet ,
Thanks for your feedback! 

This has been already addressed and will be available in the next release 1.17

**Comment by tprouvot** [comment]
1.17 is live 🚀
