### ISSUE TITLE
[data-export] Delete a single record

### ISSUE THREAD

**Issue by mickaelgudin** [tprouvot/Salesforce-Inspector-reloaded#88]
I believe it could be good to allow single record deletion :
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/39730173/a54e73a6-b7cb-485b-a2e7-0493fe4b143d)

It would make the extension closer to classic SGBDR tools such as MySQL Workbench.

I don't include bulk actions or the update of a single record here because I think those should be seperate features.

**Comment by tprouvot** [comment]
Hi @mickaelgudin,
After considering this request, I think it would change the initial purpose of the data-export page.

The delete button from the show all data page is only two clicks away 😄
