### ISSUE TITLE
Data Export - Navigate with tabulator

### ISSUE THREAD

**Issue by LexerEP** [tprouvot/Salesforce-Inspector-reloaded#89]
When adding fields to a query, it would be useful if the first tab would select the first suggested field. The "Run Export" Button is not needed in that navigation because of strg+enter shortcut. This would save many klicks :) Thank you and best regards

![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/69196690/4783756a-bf05-4cc7-bc01-057b53be97a8)

Solution:

![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/69196690/885c3fb0-79cf-4233-8484-9435739f89b3)

**Comment by tprouvot** [comment]
Hi @LexerEP , 
You were a lot to require this ! 

It is already developed and will be available in next release which should come next week. 
Already available in releaseCandidate branch if you want to use the next version in preview

**Comment by tprouvot** [comment]
1.17 is live 🚀
