### ISSUE TITLE
[popup] New UI

### ISSUE THREAD

**Issue by lberbey** [tprouvot/Salesforce-Inspector-reloaded#9]
Bonjour Thomas,

Je pense que l'interface de la popup est en décalage complet avec celle de l'outil d'import/export.
Il serait tellement plus agréable d'utiliser l'outil si tout était harmonisé.

![image](https://user-images.githubusercontent.com/4833042/143838872-84dd4da0-a533-4751-ae91-d0cc085f3e28.png)

Cordialement 🤙 ,

**Comment by tprouvot** [comment]
Hi @lberbey how are you ?
Have you check this amazing new UI ?
https://github.com/tprouvot/Salesforce-Inspector-reloaded/pull/98
