### ISSUE TITLE
[data-export] Add toLabel in completion

### ISSUE THREAD

**Issue by mickaelgudin** [tprouvot/Salesforce-Inspector-reloaded#90]
Add the toLabel function(used to retrieve the picklist label) among the available suggestions. 

![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/39730173/d5612082-180b-441f-ac78-4f47f4b641d0)

**Comment by tprouvot** [comment]
Hi @mickaelgudin thanks for suggesting this improvement !
It will be available in next release 1.17 which should be available next week

**Comment by tprouvot** [comment]
1.17 is live 🚀
