### ISSUE TITLE
[data-export] Copy data without objectnames

### ISSUE THREAD

**Issue by LexerEP** [tprouvot/Salesforce-Inspector-reloaded#94]
Hi :)

sometimes you need an export without the object names, e.g. to copy only IDs and paste them in another tool.
It would be helpful to be able to copy the export without the object names.
This could, for example, be selected via a Boolean field before the data is copied.

![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/69196690/4a1711f7-950e-4027-a642-1371584c9304)

Thank you for your great work 💯

**Comment by dufoli** [comment]
@LexerEP I have implement a such feature on https://github.com/dufoli/Salesforce-Inspector-Advanced can you check if it is fine for you.
