### ISSUE TITLE
[Shortcut] Show all data is not working

### ISSUE THREAD

**Issue by LexerEP** [tprouvot/Salesforce-Inspector-reloaded#96]
Every shortcut is working like "alt + e" or "alt + i", but not "alt + a"
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/69196690/dc0c662e-f12b-496e-bf25-107c96ba4813)

**To Reproduce**
1. Go to an account
2. Hit "alt + i" to open menue and wait until everything loaded
3. Hit "alt + a" 
4. Show all data will not open

**Expected behavior**
"Show all data" opens

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome

This was also in the old "salesforce inspector" broken. But before some years it was working ;-)

**Comment by tprouvot** [comment]
Hi @LexerEP,
This has been fixed by @pietromartino (thanks a lot for that !) and will be available in the next release 1.18.
You can test it locally with the releaseCandidate branch
